// packages/react/ui/src/components/form/date-picker/CDatePanel.tsx
import React, { useMemo, useState } from 'react'
import clsx from 'clsx'
import type { DateValue, Formatter } from './CDatePicker'
import dayjs from 'dayjs'
import { weeks } from 'casual-i18n'

interface CDatePanelProps {
  year?: number
  month?: number
  value?: DateValue
  dateRange?: [DateValue, DateValue]
  formattedDateRange?: [string, string]
  format?: string
  formatter?: Formatter
  range?: boolean
  onChange?: (value: DateValue) => void
  onDateRangeChange?: (value: [DateValue, DateValue]) => void
}
const CDatePanel = ({
  onChange,
  onDateRangeChange,
  year = new Date().getFullYear(),
  month = new Date().getMonth(),
  value = new Date(),
  dateRange = [null, null],
  formattedDateRange = ['', ''],
  format = 'YYYY-MM-DD',
  formatter = (d, f) => {
    if (!d) return ''
    return dayjs(d).format(f)
  },
  range = false,
}: CDatePanelProps) => {
  const innerFormatter = (d: DateValue) => formatter(d, format)
  const isSameDate = (d1: Date | null, d2: Date | null) => {
    return innerFormatter(d1) === innerFormatter(d2)
  }
  // 获取当前年月对应的日期
  const getCurrentYearMonthDate = () => {
    const d = new Date()
    d.setDate(1)
    d.setFullYear(year)
    d.setMonth(month)
    return d
  }

  // 设置日期
  const setDate = (date: number) => {
    const d = getCurrentYearMonthDate()
    d.setDate(date)
    const target = innerFormatter(d)
    // 单选时
    if (!range) {
      onChange?.(d)
      return
    }
    // 多选时
    const [start, end] = dateRange
    const [fStart] = formattedDateRange
    if (!start) {
      onDateRangeChange?.([d, end])
      return
    }
    if (!end) {
      onDateRangeChange?.(fStart < target ? [start, d] : [d, start])
      return
    }
    onDateRangeChange?.([d, null])
  }

  const dates = useMemo(() => {
    const d = new Date()
    d.setFullYear(year)
    d.setMonth(month)
    d.setDate(1)
    const weekNum = d.getDay()
    // 左边补空位
    const leftPads = Array(weekNum % 7)
      .fill('')
      .map((_, i) => -i)
      .reverse()
    d.setMonth(month + 1)
    d.setDate(0)
    const middle = Array(d.getDate())
      .fill(0)
      .map((_, i) => i + 1)

    // 右边补空位
    const rightPads = Array(42 - leftPads.length - middle.length)
      .fill('')
      .map((_, i) => middle.length + i + 1)

    const items = [...leftPads, ...middle, ...rightPads]
    return {
      items: items,
      start: leftPads.length,
      end: leftPads.length + middle.length
    }
  }, [month, year])

  const [hoveringDate, setHoveringDate] = useState(dateRange[1])

  const doSetHoveringDate = (date: number) => {
    const d = getCurrentYearMonthDate()
    d.setDate(date)
    setHoveringDate(d)
  }

  const isDateInRange = (date: number) => {
    const [startDate, endDate] = formattedDateRange
    if (!startDate) return false
    if (!endDate && !hoveringDate) return false
    const d = getCurrentYearMonthDate()
    d.setDate(date)
    const hovering = innerFormatter(hoveringDate)
    const target = innerFormatter(d)
    if (endDate) {
      return target >= startDate && target <= endDate
    }
    return (
      (target >= startDate && target <= hovering) ||
      (target >= hovering && target <= startDate)
    )
  }

  // 日期段选择时，判断目标日期是否为开始日期
  const isStart = (date: number) => {
    const d = getCurrentYearMonthDate()
    d.setDate(date)
    const [start, end] = formattedDateRange
    const hovering = innerFormatter(hoveringDate)
    const target = innerFormatter(d)
    if (!end) {
      return hovering <= start ? target === hovering : target === start
    }
    return start === target
  }

  // 日期段选择时，判断目标日期是否为结束日期
  const isEnd = (date: number) => {
    const d = getCurrentYearMonthDate()
    d.setDate(date)
    const [start, end] = formattedDateRange
    const hovering = innerFormatter(hoveringDate)
    const target = innerFormatter(d)
    if (!end) {
      return hovering < start ? target === start : target === hovering
    }
    return end === target
  }

  // 目标日期是否展示选中态样式
  const isSelected = (date: number) => {
    const checkTarget = new Date(year, month, date)
    if (range) {
      return dateRange.some(d => isSameDate(d, checkTarget))
    }
    return isSameDate(value, checkTarget)
  }

  // 获取单元格应当展示的日期数字
  const getDisplayDateNum = (date: number) => {
    const d = getCurrentYearMonthDate()
    d.setDate(date)
    return d.getDate()
  }

  return (
    <div className="c-date-panel c-date-picker--panel">
      <div className="c-date-panel--body">
        {weeks.map(week => (
          <div key={week} className="c-date-panel--week-item">
            {week}
          </div>
        ))}
        {dates.items.map((date, i) => (
          <div
            key={i}
            className={clsx(
              'c-date-panel--date-item',
              isStart(date) && 'c-date-panel--date-item--is-start',
              isEnd(date) && 'c-date-panel--date-item--is-end',
              isDateInRange(date) && 'c-date-panel--date-item--in-range'
            )}
            onClick={e => {
              e.stopPropagation()
              setDate(date)
            }}
            onMouseEnter={() => doSetHoveringDate(date)}
          >
            <div
              className={clsx(
                'c-date-panel--date-item--inner',
                isSelected(date) && 'c-date-panel--date-item--inner-selected',
                (i < dates.start || i >= dates.end) &&
                  'c-date-panel--date-item--inner-not-current-month'
              )}
            >
              {getDisplayDateNum(date)}
            </div>
          </div>
        ))}
      </div>
    </div>
  )
}
export default CDatePanel
export type { CDatePanelProps }

// packages/svelte/src/lib/components/form/date-picker/CDatePanel.svelte
<script>
  import clsx from '$lib/utils/clsx'

  import { weeks } from 'casual-i18n'
  /**
   * @type {number}
   */
  export let year

  /**
   * @type {number}
   */
  export let month

  /**
   * @type {Date | null}
   */
  export let value

  /**
   * @type {[Date | null, Date | null]}
   */
  export let rangeValue = [null, null]

  /**
   * @type {[string, string]}
   */
  export let formattedRangeValue = ['', '']

  /**
   * @type {(d: Date | null) => string}
   */
  export let formattor

  /**
   * @type {boolean}
   */
  export let range

  /**
   * @param {Date | null} d1
   * @param {Date | null} d2
   */
  const isSameDate = (d1, d2) => {
    return formattor(d1) === formattor(d2)
  }

  const getCurrentYearMonth = () => {
    const d = new Date()
    d.setDate(1)
    d.setFullYear(year)
    d.setMonth(month)
    return d
  }

  /**
   * @param date {number}
   */
  const setDate = date => {
    const d = getCurrentYearMonth()
    d.setDate(date)
    const target = formattor(d)
    if (range) {
      const [start, end] = rangeValue
      const [fStart] = formattedRangeValue
      if (!start) {
        rangeValue = [d, end]
        return
      }
      if (!end) {
        rangeValue = fStart < target ? [start, d] : [d, start]
        return
      }
      return
    }
    value = d
  }

  /**
   * @type { {items: number[]; start: number; end: number } }
   */
  let dates = {
    items: [],
    start: 0,
    end: 0,
  }

  const recomputeDates = () => {
    const d = new Date()
    d.setFullYear(year)
    d.setMonth(month)
    d.setDate(1)
    const weekNum = d.getDay()
    const leftPads = Array(weekNum % 7)
      .fill('')
      .map((_, i) => -i)
      .reverse()
    d.setMonth(month + 1)
    d.setDate(0)

    const middle = Array(d.getDate())
      .fill(0)
      .map((_, i) => i + 1)

    // 右边补空位
    const rightPads = Array(42 - leftPads.length - middle.length)
      .fill('')
      .map((_, i) => middle.length + i + 1)

    const items = [...leftPads, ...middle, ...rightPads]
    dates = {
      items,
      start: leftPads.length,
      end: leftPads.length + middle.length,
    }
  }

  $: {
    year
    month
    recomputeDates()
  }

  let hoveringDate = rangeValue[1]
  $: formattedHoveringDate = formattor(hoveringDate)

  /**
   * @param {number} date
   */
  const setHoveringDate = date => {
    const d = getCurrentYearMonth()
    d.setDate(date)
    hoveringDate = d
  }

  /**
   * @param { number } date
   */
  const isStart = date => {
    const d = getCurrentYearMonth()
    d.setDate(date)
    const [start, end] = formattedRangeValue
    const target = formattor(d)
    if (!end) {
      return formattedHoveringDate <= start
        ? target === formattedHoveringDate
        : target === start
    }
    return start === target
  }

  /**
   * @param {number} date
   */
  const isDateInHoveringRange = date => {
    const [start, end] = formattedRangeValue
    if (!start) return false
    if (!end && !hoveringDate) return false
    const d = getCurrentYearMonth()
    d.setDate(date)
    const target = formattor(d)
    if (end) {
      return target >= start && target <= end
    }
    return (
      (target >= start && target <= formattedHoveringDate) ||
      (target >= formattedHoveringDate && target <= start)
    )
  }

  /**
   * @param {number} date
   */
  const isEnd = date => {
    const d = getCurrentYearMonth()
    d.setDate(date)
    const [start, end] = formattedRangeValue
    const target = formattor(d)
    if (!end) {
      return formattedHoveringDate < start
        ? target === start
        : target === formattedHoveringDate
    }
    return end === target
  }

  /**
   * @param {number} date
   */
  const isSelected = date => {
    const d = getCurrentYearMonth()
    d.setDate(date)
    if (range) {
      return rangeValue.some(d2 => isSameDate(d, d2))
    }
    return isSameDate(value, d)
  }

  /**
   * @param {number} date Notice that this value can be lower than 0 or larger than 31
   */
  const getDisplaDateNum = date => {
    const d = getCurrentYearMonth()
    d.setDate(date)
    return d.getDate()
  }

  $: {
    value
    dates = dates
  }
</script>

<div class={`c-date-panel c-date-picker--panel`}>
  <div class="c-date-panel--body">
    {#each weeks as w}
      <div class="c-date-panel--week-item">
        {w}
      </div>
    {/each}
    {#each dates.items as d, i}
      <div
        class={clsx(
          `c-date-panel--date-item`,
          isStart(d) && 'c-date-panel--date-item--is-start',
          isEnd(d) && 'c-date-panel--date-item--is-end',
          isDateInHoveringRange(d) && 'c-date-panel--date-item--in-range'
        )}
        on:click|stopPropagation={() => setDate(d)}
        on:mouseenter={() => setHoveringDate(d)}
      >
        <div
          class={clsx(
            `c-date-panel--date-item--inner`,
            isSelected(d) && 'c-date-panel--date-item--inner-selected',
            (i < dates.start || i >= dates.end) &&
              'c-date-panel--date-item--inner-not-current-month'
          )}
        >
          {getDisplaDateNum(d)}
        </div>
      </div>
    {/each}
  </div>
</div>
