// packages/vue/ui/src/components/form/date-picker/CYearPanel.vue
<script setup lang="ts">
import { computed, toRefs } from 'vue'
import CDateGridPanel from './CDateGridPanel.vue'

interface OYearPanelProps {
  modelValue: Date | null
  yearRange: [number, number]
}

const props = withDefaults(defineProps<OYearPanelProps>(), {})
const emit = defineEmits<{
  (e: 'update:modelValue', newValue: Date | null): void
}>()

const { yearRange } = toRefs(props)
const years = computed(() => {
  const start = yearRange.value[0]
  const end = yearRange.value[1]
  const years = []
  for (let i = start; i <= end; i++) {
    years.push(i)
  }
  return years
})

const isSelected = (year: number) => {
  return props.modelValue?.getFullYear() === year
}
</script>
<template>
  <c-date-grid-panel
    :is-active="isSelected"
    :items="years"
    :display-formatter="year => year + ''"
    @item-click="
      year => {
        emit(
          'update:modelValue',
          new Date(
            year,
            modelValue?.getMonth() || 0,
            modelValue?.getDate() || 1
          )
        )
      }
    "
  />
</template>

// packages/svelte/src/lib/components/form/date-picker/CYearPanel.svelte
<script>
  import { createEventDispatcher } from 'svelte'

  import CGridPanel from './CGridPanel.svelte'

  /**
   * @type {Date | null}
   */
  export let value = null

  /**
   * @type {[number, number]}
   */
  export let yearRange

  /**
   * @type {number[]}
   */
  let years = []

  const getYears = () => {
    const [start, end] = yearRange
    for (let i = start; i <= end; i++) {
      years.push(i)
    }
    years = years
  }

  /**
   * @param {number} year
   */
  const isSelected = year => {
    return value ? value.getFullYear() === year : false
  }

  const dispatch = createEventDispatcher()

  /**
   * @param {number} year
   */
  const onYearClick = year => {
    if (value) {
      value = new Date(year, value.getMonth(), value.getDate())
    } else {
      value = new Date(year, 0, 1)
    }

    dispatch('year-change', value)
  }

  $: {
    yearRange
    getYears()
  }
</script>

<CGridPanel
  isActive={isSelected}
  items={years}
  displayFormattor={year => year}
  on:item-click={e => onYearClick(e.detail)}
/>
