// packages/react/ui/src/components/popup/CDialog.tsx
import { CSlot, PositionGroup } from 'casual-types'
import { matClose } from '@quasar/extras/material-icons'
import clsx from 'clsx'
import React, { CSSProperties, useEffect } from 'react'
import CButton from '../basic/button/CButton'
import CIcon from '../basic/icon/CIcon'
import CPopup from './CPopup'
import { createPortal } from 'react-dom'
import { CSSTransition } from 'react-transition-group'
import { useMemo } from 'react'

interface CDialogProps {
  /**
   * The dialog open status.
   * @zh 对话框是否打开
   */
  value: boolean
  /**
   * Emit when the dialog open status change.
   * @zh 打开/关闭触发
   */
  onChange?: (newValue: boolean) => void
  /**
   * Title
   * @zh 标题
   */
  title?: string
  /**
   * Customize the title content.
   * @zh 自定义标题
   */
  customTitle?: CSlot
  /**
   * The dialog width.
   * @zh 宽度
   */
  width?: string
  /**
   * The dialog content height. Which doesn't include header and action footer.
   * @zh 对话框体高度，不包含头部以及底部动作按钮
   */
  bodyHeight?: string
  /**
   * Determine whether the content has padding or not.
   * @zh 是否具有内容内边距
   */
  bodyPadding?: boolean
  /**
   * Determine whether the dialog has rounded border or not.
   * @zh 是否表现为圆角
   */
  rounded?: boolean
  /**
   * Determine whether to show the close icon or not.
   * @zh 是否展示关闭图标
   */
  closeIcon?: boolean
  /**
   * The horizontal align position of dialog.
   * @zh 水平位置
   */
  horizontalAlign?: 'start' | 'center' | 'end'
  /**
   * The vertical align position of dialog.
   * @zh 垂直位置
   */
  verticalAlign?: 'start' | 'center' | 'end'
  /**
   * Some additional custom CSS classes.
   * @zh 自定义对话框DOM样式类
   */
  customClass?: string
  /**
   * Some additional custom CSS styles.
   * @zh 自定义对话框DOM样式
   */
  customStyle?: CSSProperties
  /**
   * Determine whether to show the cancel button or not.
   * @zh 是否展示取消按钮
   */
  showCancelBtn?: boolean
  /**
   * The cancel button text.
   * @zh 取消按钮文字
   */
  cancelBtnLabel?: string
  /**
   * Determine whether to show the confirm button or not.
   * @zh 是否展示确认按钮
   */
  showConfirmBtn?: boolean
  /**
   * The confirm button text.
   * @zh 确认按钮文字
   */
  confirmBtnLabel?: string
  /**
   * Customize the header content.
   * @zh 自定义头部内容
   */
  customHeader?: CSlot
  /**
   * Customize the close icon.
   * @zh 自定义关闭图标
   */
  customCloseIcon?: CSlot
  /**
   * The dialog content.
   * @zh 对话框内容
   */
  children?: CSlot
  /**
   * Customize the footer content.
   * @zh 自定义底部
   */
  customFooter?: CSlot
  /**
   * Customize the footer action buttons.
   * @zh 自定义底部操作按钮
   */
  customFooterActions?: CSlot

  /**
   * Determine whether to close the dialog on backdrop clicked or not.
   * @zh 是否点击遮罩关闭对话框
   */
  closeOnClickBackdrop?: boolean

  /**
   * Determine whether to exchange the open animation order.
   * @zh 是否交换对话框动画顺序
   */
  exchangeAnimationDirection?: boolean
}

const CDialog = ({
  value,
  onChange,
  title = '',
  width = '480px',
  bodyHeight = 'auto',
  bodyPadding = true,
  rounded = true,
  closeIcon = true,
  horizontalAlign = 'center',
  verticalAlign = 'center',
  customClass,
  customStyle = {},
  cancelBtnLabel = 'Cancel',
  confirmBtnLabel = 'Confirm',
  showCancelBtn = false,
  showConfirmBtn = false,
  customHeader,
  customCloseIcon,
  children,
  customFooter,
  customFooterActions,
  customTitle,
  closeOnClickBackdrop = true,
  exchangeAnimationDirection = false,
}: CDialogProps) => {
  useEffect(() => {
    const listenKeyboard = (e: KeyboardEvent) => {
      if (e.key === 'Escape' && value) {
        onChange?.(false)
      }
    }
    window.addEventListener('keyup', listenKeyboard)
    return () => {
      window.removeEventListener('keyup', listenKeyboard)
    }
  }, [value])

  const getContent = (
    customContent: CSlot | undefined,
    defaultContent: CSlot
  ) => (customContent ? customContent : defaultContent)

  const roundedClass = useMemo(() => {
    const classMap = new Map<PositionGroup, string>([
      ['start start', `c-rounded-br-md`],
      ['start center', 'c-rounded-r-md'],
      ['start end', 'c-rounded-tr-md'],
      ['center start', 'c-rounded-b-md'],
      ['center center', 'c-rounded-md'],
      ['center end', 'c-rounded-t-md'],
      ['end start', 'c-rounded-bl-md'],
      ['end center', 'c-rounded-l-md'],
      ['end end', 'c-rounded-tl-md'],
    ])

    return classMap.get(`${horizontalAlign} ${verticalAlign}`) || ''
  }, [horizontalAlign, verticalAlign])

  return createPortal(
    <CPopup
      value={value}
      onChange={onChange}
      horizontalAlign={horizontalAlign}
      verticalAlign={verticalAlign}
      className="c-popup--dialog"
      closeOnClickBackdrop={closeOnClickBackdrop}
    >
      <CSSTransition
        in={value}
        timeout={300}
        classNames={
          exchangeAnimationDirection ? 'c-dialog-reverse' : 'c-dialog'
        }
        unmountOnExit
      >
        <div
          className={clsx(
            'c-dialog',
            rounded && roundedClass,
            customClass && customClass
          )}
          style={{
            width,
            ...customStyle,
          }}
        >
          <div className="c-dialog--header">
            {getContent(
              customHeader,
              <>
                <div className="c-dialog--title">
                  {getContent(customTitle, title)}
                </div>
                <div
                  className="c-dialog--close-btn"
                  onClick={() => onChange?.(false)}
                >
                  {customCloseIcon
                    ? customCloseIcon
                    : closeIcon && <CIcon content={matClose} />}
                </div>
              </>
            )}
          </div>
          <div
            className={clsx(
              'c-dialog--content',
              bodyPadding && 'c-px-md c-pb-md'
            )}
            style={{
              height: bodyHeight,
            }}
          >
            {children}
          </div>
          <div className="c-dialog--footer">
            {getContent(
              customFooter,
              <div className="c-row c-gutter-x-sm">
                {getContent(
                  customFooterActions,
                  <>
                    <div>
                      {showCancelBtn && (
                        <CButton
                          label={cancelBtnLabel}
                          flat
                          rounded={rounded}
                        />
                      )}
                    </div>
                    <div>
                      {showConfirmBtn && (
                        <CButton
                          label={confirmBtnLabel}
                          theme="primary"
                          rounded={rounded}
                        />
                      )}
                    </div>
                  </>
                )}
              </div>
            )}
          </div>
        </div>
      </CSSTransition>
    </CPopup>,
    document.body
  )
}

export default CDialog

export type { CDialogProps }

// packages/svelte/src/lib/components/CDialog.svelte
<script>
  import { useHorizontal, useVertical } from '$lib/hooks/usePosition'
  import clsx from '$lib/utils/clsx'
  import CPopup from './CPopup.svelte'
  import CButton from './CButton.svelte'
  import { onMount, createEventDispatcher } from 'svelte'

  const dispatch = createEventDispatcher()

  /**
   * Determine the dialog is shown or not. It's recommended to use `bind:show`
   * @type {boolean}
   */
  export let show = false

  /**
   * The title of the dialog
   * @type {string}
   */
  export let title = ''

  /**
   * The width of the whole dialog. Can be any logical HTML unit. For example: `'200px'` `'20vw'`
   * @type {string}
   */
  export let width = '40vw'

  /**
   * The body height of the dialog, which doesn't contain the header and the footer that action buttons in.
   * @type {string}
   */
  export let bodyHeight = 'auto'

  /**
   * Determine the body has a padding or not
   * @type {boolean}
   */
  export let bodyPadding = true

  /**
   * Determine the dialog has a rounded border or not
   */
  export let rounded = true

  /**
   * Determine the close icon is shown or not
   * @type {boolean}
   */
  export let closeIcon = true

  /**
   * The horizontal align position.
   *
   * ::: tip TIP
   * CDialog is implemented based on [CPopup](/components/popup)
   *
   * So, this prop and `verticalAlign` prop below is the same with CPopup
   * :::
   *
   * @type {'start' | 'center' | 'end' | undefined}
   */
  export let horizontalAlign = undefined

  /**
   * See above
   * @type {'start' | 'center' | 'end' | undefined}
   */
  export let verticalAlign = undefined

  /**
   * Customize class names
   * @type {string}
   */
  export let customClass = ''

  /**
   * Customize styles
   * @type {string}
   */
  export let customStyle = ''

  /**
   * Customize body styles
   * @type {string}
   */
  export let customBodyStyle = ''

  /**
   * Determine the whether cancel button is shown or not
   * @type {boolean}
   */
  export let showCancelBtn = false

  /**
   * The cancel button label
   * @type {string}
   */
  export let cancelBtnLabel = 'Cancel'

  /**
   * Determine the whether confirm button is shown or not
   * @type {boolean}
   */
  export let showConfirmBtn = false

  /**
   * The confirm button label
   * @type {string}
   */
  export let confirmBtnLabel = 'Confirm'

  /**
   * Exchange the animation order.
   *
   * The origin animation order is horizontal first then the vertical
   *
   * If set to `true`, the dialog animation will excute vertical first then the horizontal
   */
  export let exchangeAnimationDirection = false

  /**
   * Close the dialog when the Esc key pressed
   * @type {boolean}
   */
  export let closeOnEsc = true

  /**
   * If set to `true`. The popup would be hidden when click the backdrop.
   *
   * This prop is the same as [CPopup](/components/popup)
   */
  export let closeOnClickBackdrop = false

  const hAlign = useHorizontal(horizontalAlign)

  $: {
    if (horizontalAlign) {
      $hAlign = horizontalAlign
    }
  }
  const vAlign = useVertical(verticalAlign)

  $: {
    if (verticalAlign) {
      $vAlign = verticalAlign
    }
  }

  $: roundedClass = new Map([
    ['start start', `c-rounded-br-md`],
    ['start center', 'c-rounded-r-md'],
    ['start end', 'c-rounded-tr-md'],
    ['center start', 'c-rounded-b-md'],
    ['center center', 'c-rounded-md'],
    ['center end', 'c-rounded-t-md'],
    ['end start', 'c-rounded-bl-md'],
    ['end center', 'c-rounded-l-md'],
    ['end end', 'c-rounded-tl-md'],
  ]).get(`${$hAlign} ${$vAlign}`)

  $: forceChangeAnimationDirection =
    `${$hAlign} ${$vAlign}` === 'start center' ||
    `${$hAlign} ${$vAlign}` === 'end center'

  $: enterClassName =
    exchangeAnimationDirection || forceChangeAnimationDirection
      ? 'c-dialog-reverse-enter-active'
      : 'c-dialog-enter-active'
  $: leaveClassName =
    exchangeAnimationDirection || forceChangeAnimationDirection
      ? 'c-dialog-reverse-leave-active'
      : 'c-dialog-leave-active'

  /**
   * @param {*} node
   * @param {*} params
   */
  const dialog = (node, params) => {
    return {
      delay: 0,
      duration: 300,
    }
  }

  let inTransition = false
  let outTransition = false

  /**
   *
   * @param {*} e
   */
  const listenKeyboard = e => {
    if (e.key === 'Escape' && show && closeOnEsc) {
      show = false
    }
  }
  onMount(() => {
    window.addEventListener('keyup', listenKeyboard)
    return () => {
      window.removeEventListener('keyup', listenKeyboard)
    }
  })

  /**
   * @param {*} e
   */
  const onOutroStart = e => {
    e.target && e.target.classList.add(leaveClassName)
  }

  /**
   * @param {*} e
   */
  const onOutroEnd = e => {
    e.target && e.target.classList.add('c-dialog-exit')

    /**
     * Emit when close transition is done
     */
    dispatch('closed')
  }
</script>

<CPopup bind:show customClass="c-popup--dialog" {closeOnClickBackdrop}>
  {#if show}
    <div
      transition:dialog
      on:introstart={() => (inTransition = true)}
      on:introend={() => {
        inTransition = false
        /**
         * Emit when the open transition is done
         */
        dispatch('opened')
      }}
      on:outrostart={onOutroStart}
      on:outroend={onOutroEnd}
      class={clsx(
        'c-dialog',
        rounded && roundedClass,
        inTransition && enterClassName,
        outTransition && leaveClassName,
        customClass
      )}
      style:width
      style={customStyle}
    >
      <div class="c-dialog--header">
        <!-- 
          Customize the header content  
          This slot can override the title prop and the default close icon 
        -->
        <slot name="header">
          <div class="c-dialog--title">
            <!-- Customize the title content. This slot can override the title prop -->
            <slot name="title">
              {title}
            </slot>
          </div>
          {#if closeIcon}
            <div
              class="c-dialog--close-btn"
              on:click={() => {
                show = false
              }}
            >
              <!-- Customize the close icon -->
              <slot name="close-icon">
                <div i-majesticons-close />
              </slot>
            </div>
          {/if}
        </slot>
      </div>
      <div
        class={clsx('c-dialog--content', bodyPadding && 'c-px-md c-pb-md')}
        style={customBodyStyle}
        style:height={bodyHeight}
      >
        <!-- The default content of dialog -->
        <slot />
      </div>
      <div class="c-dialog--footer">
        <!-- 
          Customize footer content of dialog 
          This slot would override the confirm and cancel button 
        -->
        <slot name="footer">
          <div class="c-row c-gutter-x-sm">
            <!-- Customize the footer actions -->
            <slot name="actions">
              <div>
                {#if showCancelBtn}
                  <CButton
                    label={cancelBtnLabel}
                    flat
                    {rounded}
                    on:click={() => {
                      /**
                       * Emit when the default cancel button clicked
                       */
                      dispatch('cancel')
                    }}
                  />
                {/if}
              </div>
              <div>
                {#if showConfirmBtn}
                  <CButton
                    label={confirmBtnLabel}
                    {rounded}
                    on:click={() => {
                      /**
                       * Emit when the default confirm button clicked
                       */
                      dispatch('confirm')
                    }}
                  />
                {/if}
              </div>
            </slot>
          </div>
        </slot>
      </div>
    </div>
  {/if}
</CPopup>
