// packages/react/ui/src/components/interact/CDropdown.tsx
import { CSlot } from 'casual-types'
import { useClickOutside } from 'casual-ui-react'
import clsx from 'clsx'
import React, { useRef } from 'react'
interface CDropdownProps {
  /**
   * The dropdown shown status.
   * @zh 是否展开
   */
  value: boolean
  /**
   * Emit when the shown status change.
   * @zh 展开状态发生变化时触发
   */
  onChange?: (newValue: boolean) => void
  /**
   * The trigger content.
   * @zh 默认触发内容
   */
  children: CSlot
  /**
   * The dropdown content
   * @zh 下拉内容
   */
  dropContent: CSlot

  /**
   * Determine whether the dropdown is disabled or not.
   * @zh 是否禁用
   */
  disabled?: boolean
  /**
   * Determine whether the content maintain the same width with parent or not.
   * @zh 是否自动与默认内容保持一致宽度
   */
  widthWithinParent?: boolean
  /**
   * Determine whether to enable manual control or not.
   * @zh 是否手动控制
   */
  manual?: boolean
}
const CDropdown = ({
  value,
  onChange,
  children,
  dropContent,
  disabled = false,
  widthWithinParent = true,
  manual = false,
}: CDropdownProps) => {
  const dropdownDom = useRef(null)
  useClickOutside({
    domRef: dropdownDom,
    cbInside: () => {
      if (disabled || manual) return
      onChange?.(true)
    },
    cbOutside: () => {
      if (disabled || manual) return
      onChange?.(false)
    },
  })
  return (
    <div
      ref={dropdownDom}
      className={clsx('c-dropdown', value && 'c-dropdown--dropped')}
    >
      <div className="c-dropdown--trigger">{children}</div>
      <div
        className={clsx(
          'c-dropdown--drop-content',
          !widthWithinParent && 'c-dropdown--drop-content-auto-width'
        )}
      >
        {dropContent}
      </div>
    </div>
  )
}
export default CDropdown
export type { CDropdownProps }

// packages/svelte/src/lib/components/CDropdown.svelte
<script>
  import useClickOutside from '$lib/hooks/useClickOutside'
  import clsx from '$lib/utils/clsx'

  /**
   * The dropdown shown status. It is recommended to use `bind:show`.
   * @type {boolean}
   */
  export let show = false

  /**
   * Determine whether the dropdown is disabled or not.
   * @type {boolean}
   */
  export let disabled = false

  /**
   * Does the dropdown content maintain the same width with parent.
   * @type {boolean}
   */
  export let widthWithinParent = true

  /**
   * If set to `true`. Hover parent would not trigger dropdwon show.
   * @type {boolean}
   */
  export let manual = false

  const clickOutside = useClickOutside({
    cbInside: () => {
      if (disabled || manual) return
      if (!show) {
        show = true
      }
    },
    cbOutside: () => {
      if (disabled || manual) return
      show = false
    },
  })
</script>

<div use:clickOutside class={clsx('c-dropdown', show && 'c-dropdown--dropped')}>
  <div class="c-dropdown--trigger">
    <!-- The trigger content -->
    <slot />
  </div>
  <div
    class={clsx(
      'c-dropdown--drop-content',
      !widthWithinParent && 'c-dropdown--drop-content-auto-width'
    )}
  >
    <!-- The dropdown content -->
    <slot name="drop-content" />
  </div>
</div>
