// packages/react/ui/src/components/list/CInfoItem.tsx
import { CSize, CSlot } from 'casual-types'
import { CIcon, useSize } from 'casual-ui-react'
import clsx from 'clsx'
import React from 'react'

interface CInfoItemProps {
  /**
   * The icon content.
   * @zh 图标内容
   */
  icon?: string | typeof CIcon
  /**
   * The title.
   * @zh 标题
   */
  title?: string
  /**
   * The subtitle.
   * @zh 副标题
   */
  subtitle?: string
  /**
   * The vertical align direction of left and right content.
   * @zh 左右侧内容纵向对齐方式
   */
  align?: 'start' | 'center' | 'end'
  /**
   * The vertical align direction of icon and title.
   * @zh 图标与标题的对齐方式
   */
  iconAlign?: 'start' | 'center' | 'end'
  /**
   * The size.
   * @zh 尺寸
   */
  size?: CSize
  /**
   * The right content.
   * @zh 右侧追加内容
   */
  append?: CSlot
}

const CInfoItem = ({
  icon,
  title,
  subtitle,
  align = 'start',
  iconAlign = 'start',
  size,
  append,
}: CInfoItemProps) => {
  const contextSize = useSize(size)

  return (
    <div
      className={clsx(
        'c-info-item c-flex c-justify-between',
        `c-items-${align}`
      )}
    >
      <div className={clsx('c-flex c-flex-grow', `c-items-${iconAlign}`)}>
        {icon && (
          <div className={`c-mr-${contextSize}`}>
            {typeof icon === 'string' ? (
              <CIcon
                className="c-info-item--icon"
                content={icon}
              />
            ) : (
              icon
            )}
          </div>
        )}
        <div className="c-flex-grow">
          {title && <div className="c-info-item--title">{title}</div>}
          {subtitle && (
            <div className="c-info-item--subtitle c-mt-sm">{subtitle}</div>
          )}
        </div>
      </div>
      {append && append}
    </div>
  )
}

export default CInfoItem

// packages/svelte/src/lib/components/CInfoItem.svelte
<script>
  import useSize from '$lib/hooks/useSize'

  /**
   * The title of the item.
   * @type {string}
   */
  export let title = ''

  /**
   * The subtitle of the item.
   * @type {string}
   */
  export let subtitle = ''

  /**
   * The vertical align method. Base on the [CSS `align-items`](https://developer.mozilla.org/en-US/docs/Web/CSS/align-items)
   * @type {'start' | 'center' | 'end'}
   */
  export let align = 'center'

  /**
   * The icon and title vertical align method. Also based on the [CSS `align-items`](https://developer.mozilla.org/en-US/docs/Web/CSS/align-items)
   * @type {'start' | 'center' | 'end'}
   */
  export let iconAlign = 'center'

  /**
   * The size of item.
   * @type {'xs' | 'sm' | 'md' | 'lg' | 'xl'=}
   */
  export let size = undefined

  const contextSize = useSize(size)
</script>

<div class={`c-info-item c-flex cjustify-between c-items-${align}`}>
  <div class={`c-flex c-flex-grow c-items-${iconAlign}`}>
    <div class={`c-mr-${$contextSize}`}>
      <!-- The icon content -->
      <slot name="icon" />
    </div>
    <div class="c-flex-grow">
      <!-- Customize title content. Notice that this slot would override the `title` prop -->
      <slot name="title">
        <div class="c-info-item--title">
          {title}
        </div>
      </slot>
      <!-- Customize subtitle content. Notice that this slot would override the `subtitle` prop -->
      <slot name="subtitle">
        <div class="c-info-item--subtitle c-mt-sm">
          {subtitle}
        </div>
      </slot>
    </div>
  </div>
  <slot name="append" />
</div>
