// packages/react/ui/src/components/basic/tag/CTag.tsx
import React from 'react'
import { CSize, CSlot, CTheme } from 'casual-types'
import { useTheme, useSize } from 'casual-ui-react'
import { matClose } from '@quasar/extras/material-icons'
import clsx from 'clsx'
import CIcon from '../icon/CIcon'
interface CTagProps {
  /**
   * The label text.
   * @zh 标签内文字
   */
  label?: string
  /**
   * The theme color.
   * @zh 主题
   */
  theme?: CTheme
  /**
   * The size of tag.
   * @zh 尺寸
   */
  size?: CSize
  /**
   * Determine whether the tag has rounded border or not.
   * @zh 是否为圆角
   */
  rounded?: boolean
  /**
   * Determine whether the tag has a close icon or not.
   * @zh 是否可关闭，设置为<code>true</code>会展示一个关闭图标
   */
  closeable?: boolean
  /**
   * Customize the prefix content
   * @zh 自定义前置内容
   */
  prefix?: CSlot
  /**
   * Emit when the close icon clicked.
   * @zh 点击关闭图标触发
   */
  onClose?: () => void
}

const CTag = ({
  theme,
  prefix,
  label,
  closeable = false,
  size,
  rounded = false,
  onClose,
}: CTagProps) => {
  const realTheme = useTheme(theme)
  const realSize = useSize(size)

  return (
    <div
      className={clsx(
        'c-tag',
        `c-tag--theme-${realTheme}`,
        `c-h-${realSize}`,
        `c-font-${realSize}`,
        `c-px-${realSize}`,
        rounded && `c-rounded-${realSize}`
      )}
    >
      <div className="c-tag--prefix">{prefix && prefix}</div>
      <div className="c-tag--label">{label}</div>
      {closeable && (
        <div
          className={clsx('c-tag--close-icon', 'c-ml-sm')}
          onClick={e => {
            e.stopPropagation()
            onClose?.()
          }}
        >
          <CIcon content={matClose} />
        </div>
      )}
    </div>
  )
}

export default CTag

export type { CTagProps }

// packages/svelte/src/lib/components/CTag.svelte
<script>
  import useSize from '$lib/hooks/useSize'
  import useTheme from '$lib/hooks/useTheme'
  import clsx from '$lib/utils/clsx'
  import { createEventDispatcher } from 'svelte'

  /**
   * The text content of the tag
   * @type {string}
   */
  export let label = ''

  /**
   * The color theme of tag
   * @type {'primary' | 'secondary' | 'warning' | 'negative'}
   */
  export let theme = 'primary'

  /**
   * The size of tag. Notice that default value is `'md'` not `undefined`
   * @type {'xs' | 'sm' | 'md' | 'lg' | 'xl'=}
   */
  export let size = undefined

  /**
   * Determine whether the tag has a rounded border or not
   * @type {boolean}
   */
  export let rounded = false

  /**
   * If set to `true`. The tag will have a close icon which can be clicked an emit `close` event
   * @type {boolean}
   */
  export let closeable = false

  $: contextTheme = useTheme(theme)
  $: contextSize = useSize(size)

  const dispatch = createEventDispatcher()

  const onClose = () => {
    /**
     * Emit when the close icon clicked
     */
    dispatch('close')
  }
</script>

<div
  class={clsx(
    'c-tag',
    `c-tag--theme-${$contextTheme}`,
    `c-h-${$contextSize}`,
    `c-font-${$contextSize}`,
    `c-px-${$contextSize}`,
    rounded && `c-rounded-${$contextSize}`
  )}
>
  <div class="c-tag--prefix">
    <!-- Customize prefix content -->
    <slot name="prefix" />
  </div>
  <div class="c-tag--label">
    {label}
  </div>
  {#if closeable}
    <div class="c-tag--close-icon c-ml-xs" on:click|stopPropagation={onClose}>
      <div class="c-icon" i-carbon-close />
    </div>
  {/if}
</div>
