// packages/vue/ui/src/components/interact/CExpansion.vue
<script
  setup
  lang="ts"
>
import { ref, onMounted, computed } from 'vue'
import { CIcon } from 'casual-ui-vue'
import { matKeyboardArrowDown } from '@quasar/extras/material-icons'
import { useDefaultVModel } from '../../usable/useVModel'

interface CExpansionProps {
  /**
   * The icon string.
   * @zh 图标
   */
  icon?: string
  /**
   * The title.
   * @zh 标题
   */
  title?: string
  /**
   * The expand status. Can be used with <code>v-model</code>.
   * @zh 是否展开，用于<code>v-model</code>默认绑定
   */
  modelValue?: boolean
  /**
   * Determine whether to expand from top or not.
   * @zh 是否反向展开，如果设置为<code>true</code>则会从上方展开
   */
  reverse?: boolean
}

const props = withDefaults(defineProps<CExpansionProps>(), {
  title: '',
  modelValue: false,
  icon: '',
  reverse: false,
})

const emit = defineEmits<{
  /**
   * Emit when the expand status change.
   * @zh 展开状态变化时触发
   */
  (e: 'update:modelValue', newValue: boolean): void
}>()

const bodyDom = ref<HTMLDivElement | null>(null)
const initialBodyHeight = ref('auto')
const innerValue = ref(true)

useDefaultVModel(props, emit)

const onHeaderClick = () => {
  innerValue.value = !innerValue.value
}

onMounted(() => {
  initialBodyHeight.value = `${bodyDom.value?.clientHeight}px`
  innerValue.value = props.modelValue
})

const realtimeBodyHeigh = computed(() =>
  innerValue.value ? initialBodyHeight.value : 0
)

const setHeight = (h: number) => {
  initialBodyHeight.value = `${h}px`
}

defineExpose({
  setHeight,
})
</script>
<template>
  <div
    :class="['c-expansion', { 'c-expansion--expanded': innerValue }]"
    :style="`--casual-expansion-height:${realtimeBodyHeigh};`"
  >
    <div
      v-if="reverse"
      ref="bodyDom"
      class="c-expansion--body"
    >
      <!-- 
        @slot The expanded content. 
        @zh 默认展开内容 -->
      <slot v-bind="{ setHeight }" />
    </div>
    <div
      class="c-expansion--header"
      @click.stop="onHeaderClick"
    >
      <div
        v-if="icon || $slots.icon"
        class="c-expansion--icon"
      >
        <!-- 
          @slot Customize the icon content.
          @zh 自定义图标 -->
        <slot name="icon">
          <c-icon :content="icon" />
        </slot>
      </div>
      <div class="c-expansion--title">
        <!-- 
          @slot Customize the title content. 
          @zh 自定义标题 -->
        <slot name="title">
          {{ title }}
        </slot>
      </div>
      <div
        :class="[
          'c-expansion--arrow',
          { 'c-expansion--arrow-expanded': innerValue },
        ]"
      >
        <!-- 
          @slot Customize the arrow 
          @zh 自定义箭头 
            @binding {boolean} expand-status 当前展开状态
            @expandStatus_zh 当前展开状态
          -->
        <slot
          name="arrow"
          :expand-status="innerValue"
        >
          <c-icon
            class=""
            :content="matKeyboardArrowDown"
          />
        </slot>
      </div>
    </div>
    <div
      v-if="!reverse"
      ref="bodyDom"
      class="c-expansion--body"
    >
      <!-- 
        @slot The expanded content.
        @zh 默认展开内容 -->
      <slot v-bind="{ setHeight }" />
    </div>
  </div>
</template>

// packages/react/ui/src/components/interact/CExpansion.tsx
import { CSlot } from 'casual-types'
import { matKeyboardArrowDown } from '@quasar/extras/material-icons'
import clsx from 'clsx'
import React, {
  CSSProperties,
  useCallback,
  useEffect,
  useMemo,
  useRef,
  useState,
} from 'react'
import CIcon from '../basic/icon/CIcon'

interface CExpansionProps {
  /**
   * The icon content.
   * @zh 图标
   */
  icon?: CSlot
  /**
   * The title
   * @zh 标题
   */
  title?: CSlot
  /**
   * Customize the arrow
   * @zh 自定义箭头
   */
  arrow?: (expandStatus: boolean) => CSlot
  /**
   * The expand status.
   * @zh 是否展开
   */
  open?: boolean
  /**
   * Emit when expand status change.
   * @zh 设置展开态
   */
  setOpen?: (openStatus: boolean) => void
  /**
   * The expand content.
   * @zh 折叠内容
   */
  children: CSlot
  /**
   * Determine whether to expand from top.
   * @zh 是否从上方展开
   */
  reverse?: boolean
}

const CExpansion = ({
  icon,
  title = '',
  open = false,
  arrow,
  children,
  reverse = false,
}: CExpansionProps) => {
  const [innerOpen, setInnerOpen] = useState(true)
  const [initialBodyHeight, setInitialBodyHeight] = useState('auto')

  const realtimeBodyHeigh = useMemo(
    () => (innerOpen ? initialBodyHeight : 0),
    [innerOpen, initialBodyHeight]
  )

  const bodyDom = useRef<HTMLDivElement>(null)

  useEffect(() => {
    setInitialBodyHeight(`${bodyDom.current?.clientHeight}px`)
    setInnerOpen(open)
  }, [])

  const onHeaderClick = useCallback(() => {
    setInnerOpen(!innerOpen)
  }, [innerOpen])

  return (
    <div
      className={clsx('c-expansion', innerOpen && 'c-expansion--expanded')}
      style={
        {
          '--casual-expansion-height': realtimeBodyHeigh,
        } as CSSProperties
      }
    >
      {reverse && (
        <div
          ref={bodyDom}
          className="c-expansion--body"
        >
          {children}
        </div>
      )}
      <div
        className="c-expansion--header"
        onClick={onHeaderClick}
      >
        {icon && <div className="c-expansion--icon">{icon}</div>}
        <div className="c-expansion--title">{title}</div>
        <div
          className={clsx(
            'c-expansion--arrow',
            innerOpen && 'c-expansion--arrow-expanded'
          )}
        >
          {arrow ? arrow(innerOpen) : <CIcon content={matKeyboardArrowDown} />}
        </div>
      </div>
      {!reverse && (
        <div
          ref={bodyDom}
          className="c-expansion--body"
        >
          {children}
        </div>
      )}
    </div>
  )
}

export default CExpansion

export type { CExpansionProps }
