// packages/vue/ui/src/components/list/CInfoItem.vue
<script
  setup
  lang="ts"
>
import type { CSize } from 'casual-types'
import useInjectSize from '../../usable/useInjectSize'

interface CInfoItemProps {
  /**
   * 图标，<code>c-icon</code>的<code>content</code>属性
   */
  icon?: string
  /**
   * 标题
   */
  title?: string
  /**
   * 子标题
   * @default ''
   */
  subtitle?: string

  /**
   * 横向对齐方向，css的align-items属性
   */
  align?: 'start' | 'center' | 'end'

  /**
   * 图标的对齐方向，css的align-items属性
   */
  iconAlign?: 'start' | 'center' | 'end'
  /**
   * 尺寸，该值会影响标题、子标题、字体大小以及图标与标题间的间距
   */
  size?: CSize
}

const props = withDefaults(defineProps<CInfoItemProps>(), {
  title: '',
  subtitle: '',
  icon: '',
  align: 'center',
  iconAlign: 'start',
})

const { provideSize } = useInjectSize(props)
</script>
<template>
  <div
    class="c-info-item c-flex c-justify-between"
    :class="[`c-items-${align}`]"
  >
    <div
      class="c-flex c-flex-grow"
      :class="[`c-items-${iconAlign}`]"
    >
      <div :class="[`c-mr-${provideSize}`]">
        <!-- @slot 图标内容 -->
        <slot name="icon">
          <c-icon
            class="c-info-item--icon"
            v-if="icon"
            :content="icon"
          />
        </slot>
      </div>
      <div class="c-flex-grow">
        <!-- @slot 自定义标题内容 -->
        <slot name="title">
          <div class="c-info-item--title">
            {{ title }}
          </div>
        </slot>
        <!-- @slot 自定义副标题内容 -->
        <slot name="subtitle">
          <div class="c-info-item--subtitle c-mt-sm">
            {{ subtitle }}
          </div>
        </slot>
      </div>
    </div>
    <!-- @slot 自定义尾部内容 -->
    <slot name="append"> </slot>
  </div>
</template>

// packages/react/ui/src/components/list/CInfoItem.tsx
import { CSize, CSlot } from 'casual-types'
import { CIcon, useSize } from 'casual-ui-react'
import clsx from 'clsx'
import React from 'react'

interface CInfoItemProps {
  /**
   * The icon content.
   * @zh 图标内容
   */
  icon?: string | typeof CIcon
  /**
   * The title.
   * @zh 标题
   */
  title?: string
  /**
   * The subtitle.
   * @zh 副标题
   */
  subtitle?: string
  /**
   * The vertical align direction of left and right content.
   * @zh 左右侧内容纵向对齐方式
   */
  align?: 'start' | 'center' | 'end'
  /**
   * The vertical align direction of icon and title.
   * @zh 图标与标题的对齐方式
   */
  iconAlign?: 'start' | 'center' | 'end'
  /**
   * The size.
   * @zh 尺寸
   */
  size?: CSize
  /**
   * The right content.
   * @zh 右侧追加内容
   */
  append?: CSlot
}

const CInfoItem = ({
  icon,
  title,
  subtitle,
  align = 'start',
  iconAlign = 'start',
  size,
  append,
}: CInfoItemProps) => {
  const contextSize = useSize(size)

  return (
    <div
      className={clsx(
        'c-info-item c-flex c-justify-between',
        `c-items-${align}`
      )}
    >
      <div className={clsx('c-flex c-flex-grow', `c-items-${iconAlign}`)}>
        {icon && (
          <div className={`c-mr-${contextSize}`}>
            {typeof icon === 'string' ? (
              <CIcon
                className="c-info-item--icon"
                content={icon}
              />
            ) : (
              icon
            )}
          </div>
        )}
        <div className="c-flex-grow">
          {title && <div className="c-info-item--title">{title}</div>}
          {subtitle && (
            <div className="c-info-item--subtitle c-mt-sm">{subtitle}</div>
          )}
        </div>
      </div>
      {append && append}
    </div>
  )
}

export default CInfoItem
