// packages/svelte/src/lib/components/CItem.svelte
<script>
  import useSize from '$lib/hooks/useSize'
  import bem from '$lib/utils/bem'
  import { createEventDispatcher } from 'svelte'

  /**
   * The label text.
   * @type {string}
   */
  export let label = ''

  /**
   * The size of item. Notice that default value is `'md'` instead of `undefined`
   * @type {'xs' | 'sm' | 'md' | 'lg' | 'xl'=}
   */
  export let size = undefined

  /**
   * Determine whether the item is clickable or not.
   * @type {boolean}
   */
  export let clickable = false

  /**
   * Determine whether the item is active or not. Which will lead to different styles.
   * @type {boolean}
   */
  export let active = false

  const dispatch = createEventDispatcher()

  $: contextSize = useSize(size)

  const onClick = () => {
    if (clickable) {
      /**
       * Emit when the item is clicked. It only take effect when the `clickable` prop is set to `true`
       */
      dispatch('click')
    }
  }
</script>

<div
  class={`${bem('item', {
    clickable,
    active,
  })} c-font-${$contextSize} c-pa-${$contextSize}`}
  on:click|stopPropagation={onClick}
>
  <slot>
    <span class={`c-h-${$contextSize}`}>
      {label}
    </span>
  </slot>
</div>

// packages/react/ui/src/components/list/CItem.tsx
import { CSize, CSlot } from 'casual-types'
import { useSize } from 'casual-ui-react'
import clsx from 'clsx'
import React from 'react'

interface CItemProps {
  /**
   * The label text.
   * @zh 文字
   */
  label?: string | number
  /**
   * The size
   * @zh 尺寸
   */
  size?: CSize
  /**
   * Determine whether the item is clickable or not.
   * @zh 是否表现为可点击交互
   */
  clickable?: boolean
  /**
   * Determine whether the item is in active status.
   * @zh 是否处于激活态
   */
  active?: boolean
  /**
   * Emit when item is clicked.
   * @zh 点击事件触发
   */
  onClick?: () => void
  /**
   * Customize content
   * @zh 自定义内容
   */
  children?: CSlot
}

const CItem = ({
  label = '',
  size,
  clickable = false,
  active = false,
  onClick,
  children,
}: CItemProps) => {
  const contextSize = useSize(size)

  return (
    <div
      className={clsx(
        'c-item',
        clickable && 'c-item--clickable',
        active && 'c-item--active',
        `c-font-${contextSize}`,
        `c-pa-${contextSize}`
      )}
      onClick={e => {
        e.stopPropagation()
        onClick?.()
      }}
    >
      {children ? children : label}
    </div>
  )
}

export default CItem

export type { CItemProps }
