// packages/vue/ui/src/components/basic/loading/CLoading.vue
<script setup lang="ts">
interface LoadingProps {
  /**
   * 尺寸
   */
  size?: string
  /**
   * 厚度
   */
  thickness?: number
  /**
   * 颜色
   */
  color?: string
}

withDefaults(defineProps<LoadingProps>(), {
  size: '1em',
  thickness: 5,
  color: 'currentColor',
})
</script>
<template>
  <svg
    class="c-loading c-loading--mat"
    viewBox="25 25 50 50"
    :width="size"
    :height="size"
  >
    <circle
      class="c-loading--path"
      cx="50"
      cy="50"
      r="20"
      fill="none"
      :stroke="color"
      :stroke-width="thickness"
      stroke-miterlimit="10"
    ></circle>
  </svg>
</template>

// packages/react/ui/src/components/basic/loading/CLoading.tsx
import React from 'react'
import useLoadingSize from './useLoadingSize'

interface CLoadingProps {
  /**
   * 尺寸
   */
  size?: string
  /**
   * 厚度
   */
  thickness?: number
  /**
   * 颜色
   */
  color?: string
}

const CLoading = ({
  size,
  thickness = 5,
  color = 'currentColor',
}: CLoadingProps) => {
  return (
    <svg
      className="o-loading o-loading--mat"
      viewBox="25 25 50 50"
      {...useLoadingSize(size)}
    >
      <circle
        className="o-loading--path"
        cx="50"
        cy="50"
        r="20"
        fill="none"
        stroke={color}
        strokeWidth={thickness}
        strokeMiterlimit="10"
      ></circle>
    </svg>
  )
}

export default CLoading

export type { CLoadingProps }
