// packages/vue/ui/src/components/popup/CPopup.vue
<script
  setup
  lang="ts"
>
import usePosition from './usePosition'

interface CPopupProps {
  /**
   * 是否处于打卡状态
   */
  modelValue: boolean
  /**
   * 水平对齐方式
   */
  horizontalAlign?: 'start' | 'center' | 'end'
  /**
   * 垂直对齐方式
   */
  verticalAlign?: 'start' | 'center' | 'end'
  /**
   * 额外根样式类
   */
  additionClass?: string
}

const props = withDefaults(defineProps<CPopupProps>(), {
  horizontalAlign: undefined,
  verticalAlign: undefined,
  additionClass: '',
})

const { provideHorizontalAlign, provideVerticalAlign } = usePosition(props)
</script>
<template>
  <div :class="['c-popup', { 'c-popup--show': modelValue }, additionClass]">
    <Transition name="c-dialog-backdrop">
      <div
        v-if="modelValue"
        class="c-popup--backdrop"
      ></div>
    </Transition>
    <div
      :class="[
        'c-popup--content-wrapper',
        `c-items-${provideHorizontalAlign}`,
        `c-justify-${provideVerticalAlign}`,
      ]"
    >
      <div class="c-popup--content">
        <slot />
      </div>
    </div>
  </div>
</template>

// packages/react/ui/src/components/popup/CPopup.tsx
/* eslint-disable react/display-name */
import { CSlot } from 'casual-types'
import clsx from 'clsx'
import React from 'react'
import { CSSTransition } from 'react-transition-group'
interface CPopupProps {
  /**
   * 弹出层是否弹出
   */
  value: boolean
  /**
   * 水平对齐方式
   */
  horizontalAlign?: 'start' | 'center' | 'end'
  /**
   * 垂直对齐方式
   */
  verticalAlign?: 'start' | 'center' | 'end'
  /**
   * 弹出层内容
   */
  children: CSlot
  /**
   * 自定义类名
   */
  className?: string
}

const CPopup = ({
  value,
  horizontalAlign = 'center',
  verticalAlign = 'center',
  children,
  className,
}: CPopupProps) => {
  return (
    <div className={clsx('c-popup', value && 'c-popup--show', className)}>
      <CSSTransition
        in={value}
        timeout={300}
        classNames="c-dialog-backdrop"
        unmountOnExit
      >
        <div className="c-popup--backdrop"></div>
      </CSSTransition>
      <div
        className={clsx(
          'c-popup--content-wrapper',
          `c-items-${horizontalAlign}`,
          `c-justify-${verticalAlign}`
        )}
      >
        <div className={clsx('c-popup--content')}>{children}</div>
      </div>
    </div>
  )
}

export default CPopup
export type { CPopupProps }
