// packages/svelte/src/lib/components/form/CCheckboxGroup.svelte
<script>
  import { useFormProps } from '$lib/hooks/useForm'
  import useSize from '$lib/hooks/useSize'
  import CCheckbox from './CCheckbox.svelte'

  /**
   * Checkbox group current value. It is recommended to use `bind:value`.
   * @type {any[]}
   */
  export let value = []

  /**
   * The options array.
   * @type {Array<{ label: string; value: any; [k: string]: any }>}
   */
  export let options = []

  /**
   * The size of every item.
   * @type {'xs' | 'sm' | 'md' | 'lg' | 'xl'=}
   */
  export let size = undefined

  /**
   * The size of every item.
   * @type {'xs' | 'sm' | 'md' | 'lg' | 'xl'=}
   */
  export let gutterSize = undefined

  const { contextGutterSize } = useFormProps({ gutterSize })

  useSize(size)

  /**
   * @param {*} val
   */
  const onChange = val => {
    const idx = value.findIndex(v => v === val)
    if (idx === -1) {
      value = [...value, val]
    } else {
      value.splice(idx, 1)
      value = value
    }
  }
</script>

<div
  class={`c-checkbox-group c-row c-items-center c-wrap c-gutter-${$contextGutterSize}`}
>
  {#each options as op}
    <div>
      <CCheckbox
        label={op.label}
        checkedValue={op.value}
        value={value.find(v => v === op.value)}
        on:change={() => onChange(op.value)}
      />
    </div>
  {/each}
</div>

// packages/react/ui/src/components/form/CCheckboxGroup.tsx
import { CSize } from 'casual-types'
import clsx from 'clsx'
import React, { useMemo, useEffect, useState } from 'react'
import useGutterSize from '../../hooks/useGutterSize'
import CCheckbox, { CCheckboxModel } from './CCheckbox'
import { useFormItemContext } from './CFormContext'

interface CCheckboxGroupProps {
  /**
   * The options array.
   * @zh 选项数组
   */
  options?: Array<{ label: string; value: CCheckboxModel }>
  /**
   * Current selected values.
   * @zh 当前选中值数组
   */
  value: CCheckboxModel[]
  /**
   * Emit when current values change.
   * @zh 勾选值发生变化时触发
   */
  onChange?: (newValue: CCheckboxModel[]) => void
  /**
   * Custom class names.
   * @zh 自定义额外样式类
   */
  className?: string
  /**
   * The size of all checkbox inside this group.
   * @zh 勾选框间隔尺寸
   */
  gutterSize?: CSize
}

const CCheckboxGroup = ({
  options = [],
  value,
  onChange,
  className,
  gutterSize,
}: CCheckboxGroupProps) => {
  const optionsWithCheckStatus = useMemo(
    () =>
      options.map(op => ({
        ...op,
        checked: value.some(v => v === op.value),
      })),
    [options, value]
  )

  const onCheckStatusChange = (val: CCheckboxModel) => {
    const idx = value.findIndex(v => v === val)
    if (idx === -1) {
      onChange?.([...value, val])
      return
    }
    onChange?.([...value.slice(0, idx), ...value.slice(idx + 1)])
  }

  const realGutterSize = useGutterSize(gutterSize)

  const { validateCurrent } = useFormItemContext()

  const [isFirst, setIsFirst] = useState(true)

  useEffect(() => {
    if (!isFirst) {
      validateCurrent?.(value)
    }
    setIsFirst(false)
  }, [value])

  return (
    <div
      className={clsx(
        'c-checkbox-group',
        className,
        'c-row',
        'c-items-center',
        `c-gutter-${realGutterSize}`
      )}
    >
      {optionsWithCheckStatus.map(op => (
        <CCheckbox
          key={op.value as string}
          value={op.checked}
          label={op.label}
          onChange={() => onCheckStatusChange(op.value)}
        />
      ))}
    </div>
  )
}

export default CCheckboxGroup

export type { CCheckboxGroupProps }
