// packages/vue/ui/src/components/form/CCheckboxGroup.vue
<script setup lang="ts">
import { useVModel, CCheckbox } from 'casual-ui-vue'
import { computed, toRefs } from 'vue'
type CCheckboxModel = boolean | string | number

interface CCheckboxGroupProps {
  /**
   * 选项数组
   */
  options?: Array<{ label: string; value: CCheckboxModel }>
  /**
   * 当前选中值数组
   */
  modelValue: CCheckboxModel[]
}

const props = withDefaults(defineProps<CCheckboxGroupProps>(), {
  options: () => [],
})

const emit = defineEmits<{
  /**
   * 绑定值变化时触发
   */
  (e: 'update:modelValue', newValue: CCheckboxModel[]): void
}>()

const { modelValue } = toRefs(props)

const { innerValue } = useVModel<CCheckboxModel[]>(
  modelValue,
  modelValue.value,
  newValue => {
    emit('update:modelValue', newValue)
  }
)

const optionsWithCheckStatus = computed(() =>
  props.options.map(op => ({
    ...op,
    value: op.value as string,
    checked: innerValue.value.some(v => v === op.value),
  }))
)

const onCheckStatusChange = (val: CCheckboxModel) => {
  const idx = innerValue.value.findIndex(v => v === val)
  if (idx === -1) {
    innerValue.value.push(val)
    return
  }
  innerValue.value.splice(idx, 1)
}
</script>
<template>
  <div class="c-checkbox-group">
    <c-checkbox
      v-for="op in optionsWithCheckStatus"
      :key="op.value"
      :label="op.label"
      :model-value="op.checked"
      @update:model-value="onCheckStatusChange(op.value)"
    />
  </div>
</template>

// packages/react/ui/src/components/form/CCheckboxGroup.tsx
import clsx from 'clsx'
import React, { useMemo } from 'react'
import CCheckbox, { CCheckboxModel } from './CCheckbox'

interface CCheckboxGroupProps {
  /**
   * 选项数组
   */
  options?: Array<{ label: string; value: CCheckboxModel }>
  /**
   * 当前选中值数组
   */
  value: CCheckboxModel[]
  /**
   * 勾选值发生变化时触发
   */
  onChange?: (newValue: CCheckboxModel[]) => void
  /**
   * 自定义额外样式类
   */
  className?: string
}

const CCheckboxGroup = ({
  options = [],
  value,
  onChange,
  className,
}: CCheckboxGroupProps) => {
  const optionsWithCheckStatus = useMemo(
    () =>
      options.map(op => ({
        ...op,
        checked: value.some(v => v === op.value),
      })),
    [options, value]
  )

  const onCheckStatusChange = (val: CCheckboxModel) => {
    const idx = value.findIndex(v => v === val)
    if (idx === -1) {
      onChange?.([...value, val])
      return
    }
    onChange?.([...value.slice(0, idx), ...value.slice(idx + 1)])
  }

  return (
    <div className={clsx('c-checkbox-group', className)}>
      {optionsWithCheckStatus.map(op => (
        <CCheckbox
          key={op.value as string}
          value={op.checked}
          label={op.label}
          onChange={() => onCheckStatusChange(op.value)}
        />
      ))}
    </div>
  )
}

export default CCheckboxGroup

export type { CCheckboxGroupProps }
