// packages/vue/ui/src/components/form/CInput.vue
<script setup lang="ts">
import { ref, toRefs } from 'vue'
import {
  useInjectTheme,
  useVModel,
  useInjectSize,
  useSizeThemeClass,
  CLoading,
  CIcon,
  useDefaultVModel,
} from 'casual-ui-vue'
import { matHighlightOff } from '@quasar/extras/material-icons'
import type { CSize, CTheme } from 'casual-types'

interface OInputProps {
  /**
   * 输入框内的值，用于默认的<code>v-model</code>绑定
   */
  modelValue: string | number
  /**
   * 主题
   */
  theme?: CTheme
  /**
   * 是否禁用
   */
  disabled?: boolean
  /**
   * 尺寸
   */
  size?: CSize
  /**
   * 输入框预设文本
   */
  placeholder?: string
  /**
   * 是否表现为圆角
   */
  rounded?: boolean
  /**
   * 是否处于加载态
   */
  loading?: boolean
  /**
   * 内容是否可清除
   */
  clearable?: boolean
  /**
   * 是否是只读状态
   */
  readonly?: boolean
  /**
   * 是否展示前置内容与输入框之间的分割线
   */
  prefixDivider?: boolean
  /**
   * 是否展示后置内容与输入框之间的分割线
   */
  suffixDivider?: boolean
  /**
   * 是否处于聚焦态，<code>v-model:focused</code>双向绑定用
   */
  focused?: boolean
  /**
   * 是否自动根据input失去焦点事件blur
   */
  autoBlur?: boolean
  /**
   * 输入框类型
   */
  type?: 'text' | 'password'
  /**
   * 是否使用自定义颜色状态，若设置为<code>true</code>，则聚焦不会触发边框颜色变更，包括背景色、边框色
   */
  customColor?: boolean
}

const emit = defineEmits<{
  /**
   * 输入框值发生变化时触发
   * @arg {string} newValue - 新的输入框内的值
   */
  (e: 'update:modelValue', newValue: string | number): void
  /**
   * 聚焦状态发生变化时触发
   * @arg {boolean} newFocusStatus - 新的聚焦状态
   */
  (e: 'update:focused', newFocusStatus: boolean): void
  /**
   * 清除按钮触发
   */
  (e: 'clear'): void
}>()

const props = withDefaults(defineProps<OInputProps>(), {
  theme: undefined,
  disabled: false,
  placeholder: '',
  rounded: false,
  loading: false,
  clearable: false,
  readonly: false,
  prefixDivider: true,
  suffixDivider: true,
  size: undefined,
  focused: false,
  autoBlur: true,
  type: 'text',
  customColor: false,
})

const { focused } = toRefs(props)
const { provideSize: innerSize } = useInjectSize(props)

const { provideTheme: theme } = useInjectTheme(props)

const sizeThemeClasses = useSizeThemeClass({
  size: innerSize,
  theme,
  prefix: 'c-input',
})

const { innerValue: innerFocused } = useVModel(focused, false, newFocused => {
  emit('update:focused', newFocused)
})

const innerValue = useDefaultVModel(props, emit)

const inputDom = ref<HTMLInputElement | null>(null)

const onFocus = () => {
  innerFocused.value = true
}

const onBlur = () => {
  if (props.autoBlur) {
    innerFocused.value = false
  }
}

const focusInput = () => {
  inputDom.value?.focus()
}

const onClearIconClick = () => {
  emit('update:modelValue', '')
  emit('clear')
}
</script>
<template>
  <div
    :class="[
      ...sizeThemeClasses,
      { 'c-input--custom-color': customColor },
      { 'c-input--focused': innerFocused },
      { 'c-input--disabled': disabled },
      { 'c-input--readonly': readonly },
      `c-font-${innerSize}`,
      rounded && `c-rounded-${innerSize}`,
      { 'c-input--loading': loading },
      `c-h-${innerSize}`,
      `c-px-${innerSize}`,
    ]"
  >
    <div :class="['c-input--content-wrapper']">
      <div
        :class="[
          'c-input--prefix',
          { 'c-input--prefix-with-divider': prefixDivider },
          { 'c-pr-sm c-input--prefix-with-content': $slots.prefix },
        ]"
        @click="focusInput"
      >
        <!-- @slot 输入框前置内容 -->
        <slot name="prefix" />
      </div>
      <div class="c-input--input-wrapper">
        <input
          ref="inputDom"
          v-model="innerValue"
          :value="modelValue"
          :placeholder="placeholder"
          :disabled="disabled || loading"
          :readonly="readonly"
          :type="type"
          :class="[{ 'c-pl-sm': $slots.prefix }, { 'c-pr-sm': $slots.suffix }]"
          @focus="onFocus"
          @blur="onBlur"
        />
      </div>
      <div
        v-if="clearable"
        :class="[
          'c-input--clear-icon',
          { 'c-mr-sm': $slots.suffix || loading },
          { 'c-input--clear-icon-show': innerValue },
        ]"
        @click.stop="onClearIconClick"
      >
        <c-icon :content="matHighlightOff" />
      </div>
      <div
        :class="[
          'c-input--suffix',
          { 'c-input--suffix-with-divider': suffixDivider },
          {
            'c-pl-sm c-input--suffix-with-content': $slots.suffix,
          },
        ]"
        @click="focusInput"
      >
        <div :class="[{ 'c-mr-sm': loading }]">
          <!-- @slot 输入框后置内容 -->
          <slot name="suffix" />
        </div>
        <!-- @slot 自定义加载中 -->
        <slot v-if="loading" name="loading">
          <c-loading />
        </slot>
      </div>
    </div>
  </div>
</template>

// packages/react/ui/src/components/form/CInput.tsx
import { CSize, CSlot, CTheme } from 'casual-types'
import { CIcon, CLoading, useSize, useSizeThemeClass } from 'casual-ui-react'
import { matHighlightOff } from '@quasar/extras/material-icons'
import clsx from 'clsx'
import React, { useEffect, useMemo, useState } from 'react'

interface CInputProps<T = string | number> {
  /**
   * 输入框内的值
   */
  value: string | number
  /**
   * 输入框值变化触发
   */
  onChange?: (v: T) => void
  /**
   * 主题
   */
  theme?: CTheme
  /**
   * 是否禁用
   */
  disabled?: boolean
  /**
   * 输入框尺寸
   */
  size?: CSize
  /**
   * 输入框预设文本
   */
  placeholder?: string
  /**
   * 是否表现为圆角
   */
  rounded?: boolean
  /**
   * 输入框前置内容
   */
  prefix?: CSlot
  /**
   * 输入框后置内容
   */
  suffix?: CSlot
  /**
   * 是否处于加载态
   */
  loading?: boolean
  /**
   * 自定义加载内容
   */
  customLoading?: CSlot
  /**
   * 内容是否可清除
   */
  clearable?: boolean
  /**
   * 是否按照输入框表现自动失去焦点
   */
  autoBlur?: boolean
  /**
   * 失去焦点触发
   */
  setFocused?: (focused: boolean) => void
  /**
   * 是否聚焦
   */
  focused?: boolean
  /**
   * 输入框类型
   */
  type?: 'text' | 'password'
  /**
   * 是否只读
   */
  readonly?: boolean
  /**
   * 是否前置与输入框之间是否具有分割线
   */
  withPrefixDivider?: boolean
  /**
   * 是否前置与输入框之间是否具有分割线
   */
  withSuffixDivider?: boolean

  /**
   * 是否使用自定义颜色
   */
  customColor?: boolean
  /**
   * 清除图标点击触发
   */
  onClear?: () => void
}

const CInput = ({
  value,
  disabled = false,
  placeholder,
  onChange,
  theme = 'primary',
  size,
  rounded = false,
  prefix,
  suffix,
  loading = false,
  customLoading,
  clearable = false,
  autoBlur = true,
  focused = false,
  readonly = false,
  withPrefixDivider = true,
  withSuffixDivider = true,
  setFocused,
  type = 'text',
  customColor = false,
  onClear,
}: CInputProps) => {
  const [innerFocused, setInnerFocused] = useState(focused)

  useEffect(() => {
    setFocused?.(innerFocused)
  }, [innerFocused])

  useEffect(() => {
    setInnerFocused(focused)
  }, [focused])

  const canClear = useMemo(() => !!(clearable && value), [clearable, value])

  const onClearIconClick = () => {
    onChange?.('')
    onClear?.()
  }

  const onBlur = () => {
    if (autoBlur) {
      setInnerFocused(false)
    }
  }

  const contextSize = useSize(size)

  return (
    <div
      className={clsx(
        ...useSizeThemeClass({ size: contextSize, theme, prefix: 'c-input' }),
        innerFocused && `c-input--focused`,
        rounded && `c-rounded-${contextSize}`,
        loading && 'c-input--loading',
        disabled && 'c-input--disabled',
        `c-font-${contextSize}`,
        `c-px-${contextSize}`,
        `c-h-${contextSize}`,
        customColor && 'c-input--custom-color'
      )}
    >
      <div className={clsx('c-input--content-wrapper')}>
        <div
          className={clsx(
            'c-input--prefix',
            prefix && `c-pr-sm c-input--prefix-with-content`,
            withPrefixDivider && 'c-input--prefix-with-divider'
          )}
        >
          {prefix && prefix}
        </div>
        <div className="c-input--input-wrapper">
          <input
            disabled={disabled || loading}
            placeholder={placeholder}
            value={value}
            onChange={e => onChange?.(e.target.value)}
            onFocus={() => setInnerFocused(true)}
            onBlur={onBlur}
            className={clsx(prefix && `c-pl-sm`, suffix && 'c-pr-sm')}
            type={type}
            readOnly={readonly}
          />
        </div>
        {clearable && (
          <div
            className={clsx(
              'c-input--clear-icon',
              (loading || suffix) && 'c-mr-sm',
              value && 'c-input--clear-icon-show'
            )}
            onClick={onClearIconClick}
          >
            <CIcon content={matHighlightOff} />
          </div>
        )}
        <div
          className={clsx(
            'c-input--suffix',
            withSuffixDivider && 'c-input--prefix-with-divider',
            suffix && !canClear && `c-pl-sm c-input--suffix-with-content`
          )}
        >
          <div className={clsx(loading && 'c-mr-sm')}>{suffix && suffix}</div>
          {loading && (customLoading ? customLoading : <CLoading />)}
        </div>
      </div>
    </div>
  )
}

export default CInput

export type { CInputProps }
