// packages/svelte/src/lib/components/form/CRadioGroup.svelte
<script>
  import { useFormProps, useValidator } from '$lib/hooks/useForm'
  import useSize from '$lib/hooks/useSize'
  import CRadio from './CRadio.svelte'

  /**
   * Current value. It is recommended to use `bind:value`.
   * @type {string | number=}
   */
  export let value = undefined

  /**
   * The options array.
   * @type {Array<{ label: string; value: string | number }>}
   */
  export let options = []

  /**
   * The size of all radios in this group.
   * @type {'xs' | 'sm' | 'md' | 'lg' | 'xl'=}
   */
  export let size = undefined

  /**
   * The gutter size between each radio.
   * @type {'xs' | 'sm' | 'md' | 'lg' | 'xl'=}
   */
  export let gutterSize = undefined

  /**
   * If this group is in a Form context. Set this prop to `true` will validate current field when selection change.
   * @type {boolean}
   */
  export let validateOnChange = false

  const { contextGutterSize } = useFormProps({ gutterSize })

  const { validateCurrent } = useValidator()

  const mayValidate = () => {
    if (validateOnChange) {
      validateCurrent && validateCurrent()
    }
  }

  $: {
    value
    mayValidate()
  }

  useSize(size)
</script>

<div class={`c-flex c-items-center c-wrap c-gutter-x-${$contextGutterSize}`}>
  {#each options as op}
    <div>
      <CRadio bind:value selectedValue={op.value} label={op.label} />
    </div>
  {/each}
</div>

// packages/react/ui/src/components/form/CRadioGroup.tsx
import React, { useEffect } from 'react'
import clsx from 'clsx'
import { CSize } from 'casual-types'
import useGutterSize, { CGutterSizeContext } from '../../hooks/useGutterSize'
import useSize, { CSizeContext } from '../../hooks/useSize'
import CRadio from './CRadio'
import { useFormItemContext } from './CFormContext'

interface CRadioGroupProps {
  /**
   * The current value
   * @zh 当前选中值
   */
  value: any
  /**
   * Emit when the current change
   * @zh 当前选中值变化时触发的回调
   */
  onChange?: (value: any) => void
  /**
   * The options array.
   * @zh 选项数组
   */
  options: { value: string | number; label: string }[]
  /**
   * The size of all radio in this group.
   * @zh 当前组下所有的单选器的尺寸
   */
  size?: CSize
  /**
   * The gutter size between each radio.
   * @zh 选项间距大小
   */
  gutterSize?: CSize
}
const CRadioGroup = ({
  size,
  onChange,
  gutterSize,
  options = [],
  value,
}: CRadioGroupProps) => {
  const realGutterSize = useGutterSize(gutterSize)
  const { validateCurrent } = useFormItemContext()
  useEffect(() => {
    if (value) {
      validateCurrent?.(value)
    }
  }, [value])
  return (
    <CGutterSizeContext.Provider value={realGutterSize}>
      <CSizeContext.Provider value={useSize(size)}>
        <div
          className={clsx(
            'c-flex',
            'c-items-center',
            'c-wrap',
            `c-gutter-${realGutterSize}`
          )}
        >
          {options.map(option => (
            <CRadio
              key={option.value}
              value={value}
              onChange={v => {
                onChange?.(v)
              }}
              selectedValue={option.value}
              label={option.label}
            />
          ))}
        </div>
      </CSizeContext.Provider>
    </CGutterSizeContext.Provider>
  )
}
export default CRadioGroup
export type { CRadioGroupProps }
