// packages/svelte/src/lib/components/form/CSelect.svelte
<script>
  import useClickOutside from '$lib/hooks/useClickOutside'

  import { useValidator } from '$lib/hooks/useForm'
  import useSize from '$lib/hooks/useSize'
  import bem from '$lib/utils/bem'
  import clsx from '$lib/utils/clsx'
  import { onMount, tick } from 'svelte'
  import CDropdown from '../CDropdown.svelte'
  import CList from '../CList.svelte'
  import CTag from '../CTag.svelte'
  import CInput from './CInput.svelte'

  /**
   * The placeholder text. Same as [CInput](/components/CInput)
   * @type {string}
   */
  export let placheholder = ''

  /**
   * The size of select. Notice that default value is `'md'` instead of `undefined`
   * @type {'xs' | 'sm' | 'md' | 'lg' | 'xl'=}
   */
  export let size = undefined

  /**
   * The selected value(s).
   * @type {*}
   */
  export let value = ''

  /**
   * The select options
   * @type {{ label: string; value: string | number; [key: string]: any }[]}
   */
  export let options = []

  /**
   * Determine the select can select muliple choices
   */
  export let multiple = false

  /**
   * Determine whether the select has a clear icon when selected selection is not empty
   * @type {boolean}
   */
  export let clearable = false

  /**
   * Determine whether the select is diabled or not.
   * @type {boolean}
   */
  export let disabled = false

  /**
   * Determine whether the select has a rounded border or not.
   * @type {boolean}
   */
  export let rounded = false

  /**
   * @type {HTMLDivElement}
   */
  let selectDom

  /**
   * @type {HTMLDivElement}
   */
  let tagsContainer

  if (multiple && !Array.isArray(value)) {
    value = []
  }

  let inputValue = value

  let focused = false

  let selectDomHeight = -1

  let initialSelectDomHeight = -1

  $: contextSize = useSize(size)

  $: realPlaceholder = multiple
    ? value.length > 0
      ? ''
      : placheholder
    : placheholder

  $: selectDomStyle = selectDomHeight < 0 ? '' : `height:${selectDomHeight}px`

  $: selectedMultipleOptions = !multiple
    ? []
    : options.filter(op => value.some((/** @type {any} */ v) => v === op.value))

  const { hasError, clearCurrent, validateCurrent } = useValidator()

  const onSelectClick = () => {
    if (disabled) return
    if (multiple) {
      focused = !focused
    }
  }

  const onClear = () => {
    if (multiple) {
      value = []
      return
    }
    value = ''
  }

  const onArrowClick = () => {
    if (disabled) return
    if (!multiple) {
      focused = !focused
    }
  }

  /**
   *
   * @param {object} item
   * @param {string} item.label
   * @param {string | number} item.value
   */
  const onItemClick = item => {
    if (multiple && Array.isArray(value)) {
      const idx = value.findIndex((/** @type {any} */ v) => v === item.value)
      if (idx === -1) {
        value = [...value, item.value]
      } else {
        value.splice(idx, 1)
        value = value
      }
      return
    }
    value = item.value
    focused = false
  }

  $: isItemActive = (/** @type {{ value: any; }} */ item) => {
    if (multiple && Array.isArray(value)) {
      return value.some((/** @type {any} */ v) => v === item.value)
    }
    return item.value === value
  }

  const clickOutside = useClickOutside({
    cbOutside: () => {
      focused = false
    },
  })

  const recomputedSelectHeight = async () => {
    if (multiple && tagsContainer) {
      await tick()
      const newHeight = tagsContainer.clientHeight
      if (newHeight > initialSelectDomHeight) {
        selectDomHeight = newHeight
        return
      }
      selectDomHeight = initialSelectDomHeight
      return
    }
    const target = options.find(item => item.value === value)
    inputValue = target ? target.label : ''
  }

  $: {
    value
    recomputedSelectHeight()
  }

  onMount(() => {
    initialSelectDomHeight = selectDom.clientHeight
  })
</script>

<CDropdown manual bind:show={focused} {disabled}>
  <div
    bind:this={selectDom}
    class={clsx(
      bem('select', {
        disabled,
        focused,
        rounded,
        hasError: $hasError,
      }),
      rounded && `c-rounded-${$contextSize}`
    )}
    use:clickOutside
  >
    <div
      class="c-select--input-wrapper"
      style={selectDomStyle}
      on:click={onSelectClick}
    >
      {#if multiple}
        <div
          class={`c-select--placeholder c-font-${$contextSize} c-h-${$contextSize} c-px-${$contextSize}`}
        >
          {realPlaceholder}
        </div>
      {:else}
        <CInput
          bind:focused
          value={inputValue}
          {disabled}
          {clearable}
          placeholder={realPlaceholder}
          suffixDivider={false}
          customColor
          autoBlur={false}
          readonly
          on:clear={onClear}
        />
      {/if}
      <div
        class={clsx(
          'c-select--arrow',
          `c-mr-${$contextSize}`,
          focused && 'c-select--arrow-show-options'
        )}
        on:click|stopPropagation={onArrowClick}
      >
        <div i-ph-caret-down-light class="c-icon" />
      </div>
      {#if multiple}
        <div bind:this={tagsContainer} class="c-select--multiple-tags c-px-sm">
          {#each selectedMultipleOptions as { label, value }}
            <div>
              <CTag
                {label}
                size="xs"
                rounded
                closeable
                on:close={() => onItemClick({ label, value })}
              />
            </div>
          {/each}
        </div>
      {/if}
    </div>
  </div>

  <div slot="drop-content" class={`c-py-${$contextSize}`}>
    <CList
      items={options}
      activeFn={isItemActive}
      clickable
      on:item-click={e => onItemClick(e.detail)}
    />
  </div>
</CDropdown>

// packages/react/ui/src/components/form/CSelect.tsx
import { CSize } from 'casual-types'
import { useSize, CSizeContext, CIcon } from 'casual-ui-react'
import { matKeyboardArrowDown } from '@quasar/extras/material-icons'
import clsx from 'clsx'
import React, { useEffect, useMemo, useRef, useState } from 'react'
import CTag from '../basic/tag/CTag'
import CDropdown from '../interact/CDropdown'
import CList from '../list/CList'
import CInput from './CInput'
import { useFormItemContext } from './CFormContext'

/**
 * 选择器值类型
 */
type CSelectModelValue = string | number | Array<string | number>

type OOption = {
  label: string
  value: any
  [otherKey: string | number | symbol]: any
}

interface CSelectProps {
  /**
   * The placeholder text.
   * @zh 预设文本
   */
  placeholder?: string
  /**
   * The size of select.
   * @zh 尺寸
   */
  size?: CSize
  /**
   * The value of current selected option.
   * @zh 当前选中选项对应的值
   */
  value: CSelectModelValue
  /**
   * Emit when the current selected value change.
   * @zh 当前选中值变化时触发
   */
  onChange: (newValue: CSelectModelValue) => void
  /**
   * The options array.
   * @zh 选项数组
   */
  options?: OOption[]
  /**
   * Determine whether the selected value is clearable or not.
   * @zh 是否内容可清除
   */
  clearable?: boolean
  /**
   * Determine the select can have multiple selected values.
   * @zh 是否可多选
   */
  multiple?: boolean
  /**
   * Determine whether the select is disabled or not.
   * @zh 是否禁用
   */
  disabled?: boolean
}

const CSelect = ({
  placeholder,
  size,
  options = [],
  clearable,
  onChange,
  value,
  multiple = false,
  disabled = false,
}: CSelectProps) => {
  const selectDom = useRef<HTMLDivElement>(null)
  const tagsDom = useRef<HTMLDivElement>(null)

  const [initialSelectDomHeight, setInitialSelectDomHeight] = useState(0)
  const [selectDomHeight, setSelectDomHeight] = useState(-1)

  const selectDomStyle = useMemo(() => {
    if (selectDomHeight < 1) return {}
    return {
      height: `${selectDomHeight}px`,
    }
  }, [selectDomHeight])

  const [inputValue, setInputValue] = useState<string | number>('')
  const contextSize = useSize(size)
  const [focused, setFocused] = useState(false)

  const realPlaceholder = useMemo(() => {
    if (!multiple) return placeholder
    return (value as any[]).length > 0 ? '' : placeholder
  }, [placeholder, value])

  const selectedOptions = useMemo(() => {
    if (!multiple) return []
    return options.filter(op => (value as any[]).some(v => v === op.value))
  }, [multiple, value, options])

  useEffect(() => {
    setInitialSelectDomHeight(selectDom.current?.clientHeight || -1)
  }, [])

  const { hasError, validateCurrent } = useFormItemContext()

  const [isFirst, setIsFirst] = useState(true)

  useEffect(() => {
    if (!isFirst) {
      validateCurrent?.(value)
    }
    setIsFirst(false)
    if (multiple) {
      const newHeight = tagsDom.current?.clientHeight || -1
      if (newHeight > initialSelectDomHeight) {
        setSelectDomHeight(newHeight)
        return
      }
      setSelectDomHeight(initialSelectDomHeight)
      return
    }
    setInputValue(options.find(item => item.value === value)?.label || '')
  }, [value])

  const onItemClick = (item: OOption) => {
    if (multiple) {
      const selectedValues = value as any[]
      const idx = selectedValues.findIndex(v => v === item.value)
      if (idx === -1) {
        onChange([...selectedValues, item.value])
        return
      }
      onChange([
        ...selectedValues.slice(0, idx),
        ...selectedValues.slice(idx + 1),
      ])
      return
    }
    onChange(item.value)
    setFocused(false)
  }

  const onSelectClick = () => {
    if (disabled) return

    if (multiple) {
      setFocused(!focused)
    }
  }

  const onArrowClick = () => {
    if (disabled) return
    if (!multiple) {
      setFocused(!focused)
    }
  }

  const isItemActive = (item: OOption) => {
    if (multiple) {
      return (value as any[]).some(v => v === item.value)
    }
    return item.value === value
  }

  const onClear = () => {
    if (multiple) {
      onChange?.([])
      return
    }
    onChange?.('')
  }

  return (
    <CSizeContext.Provider value={contextSize}>
      <CDropdown
        value={focused}
        onChange={setFocused}
        disabled={disabled}
        dropContent={
          <div
            className={clsx(
              `c-py-${contextSize}`,
              focused && 'c-select--options-show'
            )}
          >
            <CList
              itemKey="value"
              items={options}
              activeFn={isItemActive}
              clickable
              onItemClick={onItemClick}
            />
          </div>
        }
      >
        <div
          ref={selectDom}
          className={clsx(
            'c-select',
            focused && 'c-select--focused',
            `c-font-${contextSize}`,
            disabled && 'c-select--disabled',
            hasError && 'c-select--has-error'
          )}
          style={selectDomStyle}
        >
          <div
            className="c-select--input-wrapper"
            onClick={onSelectClick}
          >
            {multiple ? (
              <div
                className={clsx(
                  'c-select--placeholder',
                  `c-h-${contextSize}`,
                  `c-px-${contextSize}`
                )}
              >
                {realPlaceholder}
              </div>
            ) : (
              <CInput
                value={inputValue}
                onChange={v => setInputValue(v)}
                focused={focused}
                setFocused={setFocused}
                placeholder={realPlaceholder}
                autoBlur={false}
                clearable={clearable}
                readonly
                withSuffixDivider={false}
                customColor
                disabled={disabled}
                onClear={onClear}
              />
            )}
            <div
              className={clsx(
                'c-select--arrow',
                `c-mr-${contextSize}`,
                focused && `c-select--arrow-show-options`
              )}
              onClick={onArrowClick}
            >
              <CIcon content={matKeyboardArrowDown} />
            </div>
            {multiple && (
              <div
                ref={tagsDom}
                className={clsx('c-select--multiple-tags', 'c-px-sm')}
              >
                {selectedOptions.map(op => (
                  <div
                    className=""
                    key={op.value}
                  >
                    <CTag
                      label={op.label}
                      size="xs"
                      rounded
                      closeable
                      onClose={() => onItemClick(op)}
                    />
                  </div>
                ))}
              </div>
            )}
          </div>
        </div>
      </CDropdown>
    </CSizeContext.Provider>
  )
}

export default CSelect

export type { CSelectProps }
