// packages/svelte/src/lib/components/form/CToggle.svelte
<script>
  import useSize from '$lib/hooks/useSize'
  import bem from '$lib/utils/bem'
  import clsx from '$lib/utils/clsx'

  /**
   * The toggle label text. It is recommended to use `bind:value`.
   * @type {string}
   */
  export let label = ''

  /**
   * The size of toggle. Notice that the default value is `'md'` instead of `undefined`
   * @type {'xs' | 'sm' | 'md' | 'lg' | 'xl'=}
   */
  export let size = undefined

  /**
   * The current value of toggle.
   * @type {any}
   */
  export let value = false

  /**
   * The value passed to `value` prop when the toggle is on.
   * @type {any}
   */
  export let checkedValue = true

  /**
   * The value passed to `value` prop when the toggle is off.
   * @type {any}
   */
  export let uncheckValue = false

  /**
   * Determine whether the toggle is dislabed or not.
   * @type {boolean}
   */
  export let disabled = false

  const contextSize = useSize(size)

  $: checked = value === checkedValue

  const toggle = () => {
    if (disabled) return
    if (value === checkedValue) {
      value = uncheckValue
      return
    }
    value = checkedValue
  }
</script>

<div
  class={clsx(
    bem('toggle', {
      checked,
      disabled,
    }),
    `c-h-${$contextSize}`,
    `c-font-${$contextSize}`,
    `c-toggle--size-${$contextSize}`
  )}
  on:click={toggle}
>
  <div class="c-toggle--track">
    <div class="c-toggle--dot" />
  </div>
  <div class="c-toggle--label">
    {label}
  </div>
</div>

// packages/react/ui/src/components/form/CToggle.tsx
import { CSize } from 'casual-types'
import { useSize } from 'casual-ui-react'
import clsx from 'clsx'
import React from 'react'

interface CToggleProps {
  /**
   * The label text
   * @zh 文案
   */
  label?: string
  /**
   * The size
   * @zh 尺寸
   */
  size?: CSize
  /**
   * The current value.
   * @zh 当前值
   */
  value: any
  /**
   * Emit when current value change
   * @zh 值变化时触发
   */
  onChange?: (newValue: any) => void
  /**
   * The value used when the toggle is on
   * @zh 打开时的值
   */
  checkValue?: any
  /**
   * The value used when the toggle is off
   * @zh 关闭时的值
   */
  uncheckValue?: any
  /**
   * Determine wether the toggle is disabled or not.
   * @zh 是否禁用
   */
  disabled?: boolean
}

const CToggle = ({
  size,
  label = '',
  value,
  onChange,
  checkValue = true,
  uncheckValue = false,
  disabled = false,
}: CToggleProps) => {
  const realSize = useSize(size)

  const onToggle = () => {
    if (disabled) return
    onChange?.(value === checkValue ? uncheckValue : checkValue)
  }

  return (
    <div
      className={clsx(
        'c-toggle',
        `c-toggle--size-${realSize}`,
        `c-h-${realSize}`,
        `c-font-${realSize}`,
        value === checkValue && 'c-toggle--checked',
        disabled && 'c-toggle--disabled'
      )}
      onClick={onToggle}
    >
      <div className="c-toggle--track">
        <div className="c-toggle--dot"></div>
      </div>
      <div className="c-toggle--label">{label}</div>
    </div>
  )
}

export default CToggle

export type { CToggleProps }
