// packages/vue/ui/src/components/basic/loading/CLoadingPie.vue
<template>
  <svg
    class="c-loading"
    viewBox="0 0 100 100"
    preserveAspectRatio="xMidYMid"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      d="M0 50A50 50 0 0 1 50 0L50 50L0 50"
      fill="currentColor"
      opacity="0.5"
    >
      <animateTransform
        attributeName="transform"
        type="rotate"
        from="0 50 50"
        to="360 50 50"
        dur="0.8s"
        repeatCount="indefinite"
      ></animateTransform>
    </path>
    <path
      d="M50 0A50 50 0 0 1 100 50L50 50L50 0"
      fill="currentColor"
      opacity="0.5"
    >
      <animateTransform
        attributeName="transform"
        type="rotate"
        from="0 50 50"
        to="360 50 50"
        dur="1.6s"
        repeatCount="indefinite"
      ></animateTransform>
    </path>
    <path
      d="M100 50A50 50 0 0 1 50 100L50 50L100 50"
      fill="currentColor"
      opacity="0.5"
    >
      <animateTransform
        attributeName="transform"
        type="rotate"
        from="0 50 50"
        to="360 50 50"
        dur="2.4s"
        repeatCount="indefinite"
      ></animateTransform>
    </path>
    <path
      d="M50 100A50 50 0 0 1 0 50L50 50L50 100"
      fill="currentColor"
      opacity="0.5"
    >
      <animateTransform
        attributeName="transform"
        type="rotate"
        from="0 50 50"
        to="360 50 50"
        dur="3.2s"
        repeatCount="indefinite"
      ></animateTransform>
    </path>
  </svg>
</template>

// packages/svelte/ui/src/components/loadings/CLoadingPie.svelte
  <svg
    class="c-loading"
    viewBox="0 0 100 100"
    preserveAspectRatio="xMidYMid"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      d="M0 50A50 50 0 0 1 50 0L50 50L0 50"
      fill="currentColor"
      opacity="0.5"
    >
      <animateTransform
        attributeName="transform"
        type="rotate"
        from="0 50 50"
        to="360 50 50"
        dur="0.8s"
        repeatCount="indefinite"
      ></animateTransform>
    </path>
    <path
      d="M50 0A50 50 0 0 1 100 50L50 50L50 0"
      fill="currentColor"
      opacity="0.5"
    >
      <animateTransform
        attributeName="transform"
        type="rotate"
        from="0 50 50"
        to="360 50 50"
        dur="1.6s"
        repeatCount="indefinite"
      ></animateTransform>
    </path>
    <path
      d="M100 50A50 50 0 0 1 50 100L50 50L100 50"
      fill="currentColor"
      opacity="0.5"
    >
      <animateTransform
        attributeName="transform"
        type="rotate"
        from="0 50 50"
        to="360 50 50"
        dur="2.4s"
        repeatCount="indefinite"
      ></animateTransform>
    </path>
    <path
      d="M50 100A50 50 0 0 1 0 50L50 50L50 100"
      fill="currentColor"
      opacity="0.5"
    >
      <animateTransform
        attributeName="transform"
        type="rotate"
        from="0 50 50"
        to="360 50 50"
        dur="3.2s"
        repeatCount="indefinite"
      ></animateTransform>
    </path>
  </svg>
