// packages/react/ui/src/components/form/CFormItem.tsx
import React, { useMemo } from 'react'
import clsx from 'clsx'
import { CRule, CSize, CLabelDirection } from 'casual-types'
import { CFormItemContext, useFormContext } from './CFormContext'
import useSize, { CSizeContext } from '../../hooks/useSize'
import useGutterSize, { CGutterSizeContext } from '../../hooks/useGutterSize'

interface CFormItemProps {
  /**
   * 对应表单中的项的名称
   */
  field?: string
  /**
   * 文本提示
   */
  label?: string
  /**
   * 文本提示宽度
   */
  labelWidth?: string
  /**
   * 文本提示与表单元素对齐方向
   */
  labelDirection?: 'row' | 'row-reverse' | 'column' | 'column-reverse'
  /**
   * 文本提示对齐方向，表现为text-align的值
   */
  labelAlign?: 'left' | 'right' | 'center'
  /**
   * 表单项所占列数，该值可覆盖父级表单的col属性
   */
  col?: number
  /**
   * 具体的表单组件
   */
  children?: JSX.Element
  /**
   * 验证规则
   */
  rules?: CRule[]
  /**
   * 尺寸
   */
  size?: CSize
  /**
   * 元素间隔尺寸
   */
  gutterSize?: CSize
}
const CFormItem = ({
  field,
  label,
  size,
  gutterSize,
  labelWidth,
  labelAlign,
  labelDirection,
  rules,
  col,
  children,
}: CFormItemProps) => {
  const formContextValue = useFormContext({
    labelAlign,
    labelDirection,
    labelWidth,
    col,
  })

  if (field && rules) {
    formContextValue.addValidator?.(field, rules)
  }

  const validateCurrent = (v: any) => {
    if (field) {
      formContextValue.validateField?.(field, v)
    }
  }

  const hasError = useMemo(() => {
    if (!formContextValue.errors) return false
    if (!field) return false
    return formContextValue.errors[field]
  }, [formContextValue.errors])

  const clearCurrent = () => {
    if (field) {
      formContextValue.clearField?.(field)
    }
  }

  const realSize = useSize(size)

  const getLabelMarginPosition = (direction: CLabelDirection) => {
    return new Map<CLabelDirection, 't' | 'b' | 'l' | 'r'>([
      ['row', 'r'],
      ['row-reverse', 'l'],
      ['column', 'b'],
      ['column-reverse', 't'],
    ]).get(direction)
  }

  return (
    <CFormItemContext.Provider
      value={{
        hasError,
        clearCurrent,
        validateCurrent,
      }}
    >
      <CSizeContext.Provider value={realSize}>
        <CGutterSizeContext.Provider value={useGutterSize(gutterSize)}>
          <div
            className={clsx(
              'c-form-item',
              `c-col-${col}`,
              `c-${formContextValue.labelDirection}`,
              `c-col-${formContextValue.col}`,
              formContextValue.labelDirection === 'column' ||
                formContextValue.labelDirection === 'column-reverse'
                ? 'c-items-start'
                : 'c-items-center'
            )}
          >
            <div
              className={clsx(
                'c-form-item--label',
                `c-font-${realSize}`,
                `c-m${getLabelMarginPosition(
                  formContextValue.labelDirection
                )}-${realSize}`,
                `c-text-${formContextValue.labelAlign}`
              )}
            >
              {label}
            </div>
            <div className="c-form-item--content-wrapper">{children}</div>
            {hasError && (
              <div className="c-form-item--error-tip">{hasError}</div>
            )}
          </div>
        </CGutterSizeContext.Provider>
      </CSizeContext.Provider>
    </CFormItemContext.Provider>
  )
}
export default CFormItem
export type { CFormItemProps }

// packages/vue/ui/src/components/form/CFormItem.vue
<script lang="ts" setup>
import type { CSize, CRule } from 'casual-types'
import useFormProps, { type LabelDirection } from './useFormProps'

interface CFormItemProps {
  /**
   * 对应表单中的项的名称
   */
  field?: string
  /**
   * 文本提示
   */
  label?: string
  /**
   * 文本提示宽度
   * @default '100px'
   */
  labelWidth?: string
  /**
   * 表单项占用的列数，可覆盖表单整体的col属性，可用于为项定制列宽
   * @default 6
   */
  col?: number
  /**
   * 尺寸
   */
  size?: CSize
  /**
   * 验证规则
   */
  rules?: CRule[]
  /**
   * 提示文字与表单项排列方向，可覆盖表单整体的label-direction属性
   * @default 'row'
   */
  labelDirection?: LabelDirection
  /**
   * 文字对齐方式，表现为text-align的对应值，可覆盖表单整体的label-align属性
   * @default 'left'
   */
  labelAlign?: 'left' | 'center' | 'right'
}

const props = withDefaults(defineProps<CFormItemProps>(), {
  label: '',
  labelWidth: undefined,
  col: undefined,
  size: undefined,
  rules: () => [],
  field: undefined,
  labelDirection: undefined,
  labelAlign: undefined,
})

const { col, labelDirection, size, labelWidth, labelAlign } =
  useFormProps(props)

const isLabelVertical = (direction: LabelDirection) => {
  return direction === 'column' || direction === 'column-reverse'
}

const getLabelMarginPosition = (direction: LabelDirection) => {
  return new Map<LabelDirection, 't' | 'b' | 'l' | 'r'>([
    ['row', 'r'],
    ['row-reverse', 'l'],
    ['column', 'b'],
    ['column-reverse', 't'],
  ]).get(direction)
}
</script>
<template>
  <div
    :class="[
      'c-form-item',
      `c-col-${col}`,
      `c-${labelDirection}`,
      isLabelVertical(labelDirection) ? 'c-items-start' : 'c-items-center',
    ]"
  >
    <!-- 
      @slot 表单项内容 
    -->
    <div
      :class="[
        'c-form-item--label',
        `c-font-${size}`,
        `c-m${getLabelMarginPosition(labelDirection)}-${size}`,
        `c-text-${labelAlign}`,
      ]"
      :style="{
        width: labelWidth,
      }"
    >
      {{ label }}
    </div>
    <slot />
  </div>
</template>
