// packages/svelte/src/lib/components/form/CForm.svelte
<script context="module">
  /**
   * The errorStatus inject key. Example:
   *
   * ```ts
   * import { getContext } from 'svelte'
   * import { errorStatusKey } from 'casual-ui-svelte/components/form/CForm.svelte'
   * const errorStaus: ErrorStatus = getContext(errorStatusKey)
   * type ErrorStatus = Writable<Record<string, string | false>>
   * ```
   * @type {symbol}
   */
  export const errorStatusKey = Symbol('errorStatus')

  /**
   * The function to validate specify field. Example:
   *
   * ```ts
   * import { validateSomeFieldKey } from 'casual-ui-svelte/components/form/CForm.svelte'
   * import { getContext } from 'svelte'
   * const validateSomeField = getContext(validateSomeFieldKey)
   *
   * // At some time
   * validateSomeFiled?.('field')
   * ```
   */
  export const validateSomeFieldKey = Symbol('validateSomeField')

  /**
   * The function to clear specify field validate status. Example:
   *
   * ```ts
   * import { clearSomeFieldKey } from 'casual-ui-svelte/components/form/CForm.svelte'
   * import { getContext } from 'svelte'
   * const clearSomeField = getContext(clearSomeFieldKey)
   *
   * // At some time
   * clearSomeField?.('field')
   * ```
   */
  export const clearSomeFieldKey = Symbol('clearSomeField')
</script>

<script>
  import { useFormProps } from '$lib/hooks/useForm'
  import { setContext } from 'svelte'
  import { writable } from 'svelte/store'
  /**
   * The whole form data
   * @type {Record<string, any>}
   */
  export let value = {}

  /**
   * The validators of each form item.
   * @type {Record<string, Array<(val: any) => string | false | Promise<string | false>>>}
   */
  export let rules = {}

  /**
   * The label width of whole form. Notice that the default value is `'80px'` instead of `undefined`.
   * @type {string=}
   */
  export let labelWidth = undefined

  /**
   * The col span of each form item. Total cols are 12. Notice that default value is `6` instead of `undefined`
   * @type {number=}
   */
  export let col = undefined

  /**
   * Label and form component arrangement direction.
   *
   * Notice that the defualt value is `'row'` instead of `undefined`.
   *
   * This prop use [CSS flex-direction](https://developer.mozilla.org/en-US/docs/Web/CSS/flex-direction).
   * @type {'row' | 'row-reverse' | 'column' | 'column-reverse'=}
   */
  export let labelDirection = undefined

  /**
   * The label itself arrangement direction.
   *
   * Notice that the default value is `'left'` instead of `undefined`
   *
   * This prop use [CSS text-align](https://developer.mozilla.org/en-US/docs/Web/CSS/text-align)
   * @type {'left' | 'center' | 'right'=}
   */
  export let labelAlign = undefined

  /**
   * The size of whole form.
   *
   * Notice that the default value is `'md'` instead of `undefined`.
   *
   * ::: tip TIP
   * This prop will affect all the components that holds the size props.
   * :::
   * @type {'xs' | 'sm' | 'md' | 'lg' | 'xl'=}
   */
  export let size = undefined

  /**
   * The gutte size between label and form component
   * @type {'xs' | 'sm' | 'md' | 'lg' | 'xl'=}
   */
  export let gutterSize = 'md'

  /**
   * The falg that determine form is in validating or not.
   * @type {boolean}
   */
  export let validating = false

  const formProps = useFormProps({
    labelAlign,
    labelDirection,
    labelWidth,
    size,
    gutterSize,
    col,
  })

  const { contextGutterSize } = formProps

  /**
   * @type {import('svelte/types/runtime/store').Writable<Record<string, false | string>>}
   */
  const errorStatus = writable(
    Object.keys(value).reduce(
      (obj, f) => ({
        ...obj,
        [f]: false,
      }),
      {}
    )
  )

  setContext(errorStatusKey, errorStatus)

  /**
   * Validate a single field
   * @param {string} f
   */
  const validateSomeField = async f => {
    const validators = rules[f]
    if (!validators) return
    for (let i = 0; i < validators.length; i++) {
      const validator = validators[i]
      const r = await validator(value[f])
      if (r) {
        $errorStatus = {
          ...$errorStatus,
          [f]: r,
        }
        break
      }
    }
  }

  /**
   * Clear a specified field validate status
   * @param {string} f
   */
  const clearSomeField = f => {
    $errorStatus = {
      ...$errorStatus,
      [f]: false,
    }
  }

  setContext(validateSomeFieldKey, validateSomeField)
  setContext(clearSomeFieldKey, clearSomeField)

  /**
   * Validate all fields
   */
  const validateAll = () =>
    new Promise(resolve => {
      validating = true
      const validatorPromises = Object.keys(rules).map(validateSomeField)
      Promise.all(validatorPromises)
        .then(() => {
          if (Object.values($errorStatus).every(v => !v)) {
            resolve(void 0)
          }
        })
        .finally(() => {
          validating = false
        })
    })

  /**
   * Clear all fields validate status
   */
  const clearAll = () => {
    $errorStatus = Object.keys(value).reduce(
      (obj, f) => ({
        ...obj,
        [f]: false,
      }),
      {}
    )
  }

  export { validateAll, validateSomeField, clearAll, clearSomeField }
</script>

<div
  class={`c-form c-row c-items-center c-wrap c-gutter-${$contextGutterSize}`}
>
  <slot>
    <!-- TODO: generate form with items -->
  </slot>
</div>

// packages/vue/ui/src/components/form/CForm.vue
<script lang="ts">
export const errorKey = Symbol('errorStatus')
export const validatorsKey = Symbol('validators')
</script>

<script setup lang="ts">
import useFormProps, { type LabelDirection } from './useFormProps'
import CFormItem from './CFormItem.vue'
import type { Component } from 'vue'
import { provide, ref } from 'vue'
import type { CRule, CSize } from 'casual-types'
import { useDefaultVModel } from '../../usable/useVModel'
import { nextTick } from 'process'

interface Option {
  value: string | number
  label: string
}

type FormItemComponent =
  | 'input'
  | 'select'
  | 'checkbox'
  | 'checkbox-group'
  | 'radio'
  | 'radio-group'
  | 'date-picker'
  | 'toggle'
  | Component

/**
 * The form config item.
 * @zh 表单项配置
 */
interface CFormItemConfig {
  /**
   * The component.
   * @zh 表单项类型，对应需要渲染的组件
   */
  component?: FormItemComponent
  /**
   * The props passed to the component.
   * @zh 需要传递给组件的属性选项
   */
  componentProps?: object
  /**
   * The field key of whole form data.
   * @zh 对应表单数据字段名称
   */
  field: string
  /**
   * The label text
   * @zh 表单项文案提示
   */
  label?: string
  /**
   * The validators
   * @zh 验证规则
   */
  rules?: CRule[]
  /**
   * The col span
   * @zh 项的自定义列宽
   */
  col?: number
}

interface CFormProps {
  /**
   * The form items config
   * @zh 表单项配置
   */
  items?: CFormItemConfig[]
  /**
   * The whole form data. Can be used with <code>v-model</code>.
   * @zh 表单绑定值，用于<code>v-model</code>
   */
  modelValue?: Record<string, any>
  /**
   * The label width.
   * @zh 表单项提示文案长度
   * @default '100px'
   */
  labelWidth?: string
  /**
   * The col span
   * @zh 每个表单项占用的列数
   * @default 6
   */
  col?: number
  /**
   * The label and form component direction.
   * @zh 文本排列方向，表现为flex-direction的对应值
   * @default 'row'
   */
  labelDirection?: LabelDirection
  /**
   * The label align method.
   * @zh 文字对齐方式，表现为text-align的对应值
   * @default 'left'
   */
  labelAlign?: 'left' | 'center' | 'right'
  /**
   * The size. It will affect all components within.
   * @zh 尺寸
   * @default 'md'
   */
  size?: CSize
  /**
   * The gutter size.
   * @zh 表单项间隔尺寸
   */
  gutterSize?: CSize

  /**
   * Determine whether the whole form is in validating or not. Can be used with <code>v-model:validating</code>. It maybe helpful when some async status loading is required
   * @zh 是否在验证中，可用于<code>v-model:validating</code>绑定，在具有异步验证规则时可能会需要这个属性用作一些状态展示
   */
  validating?: boolean
}

const emit = defineEmits<{
  /**
   * Emit when the form data is changed.
   * @zh 表单绑定值变化时触发
   * @arg {any} newModelValue_zh 新的绑定值
   * @arg {any} newModelValue new form data
   */
  (e: 'update:modelValue', newModelValue: object): void
  /**
   * Emit when the validating status change.
   * @zh 表单验证进行中状态变更触发
   * @arg {boolean} newValidating_zh 新的验证状态
   * @arg {boolean} newValidating new validating status
   */
  (e: 'update:validating', newValidating: boolean): void
}>()

const props = withDefaults(defineProps<CFormProps>(), {
  items: () => [],
  modelValue: () => ({}),
  labelWidth: undefined,
  col: undefined,
  labelDirection: undefined,
  size: undefined,
  gutterSize: 'md',
  labelAlign: undefined,
  validating: false,
})

const innerValue = useDefaultVModel(props, emit)
useFormProps(props)

/**
 * Determine which component should be used to render the form item.
 * @zh 决定渲染何种组件，默认渲染输入框
 */
const getComponent = (component?: FormItemComponent) => {
  if (!component) return 'c-input'
  if (typeof component === 'string') {
    return `c-${component}`
  }
  return component
}

const errorStatus = ref<{
  [key: string]: {
    error: boolean
    message: string
  }
}>(
  props.items.reduce(
    (obj, { field }) => ({
      ...obj,
      [field]: {
        error: false,
        message: '',
      },
    }),
    {}
  )
)

provide(errorKey, errorStatus)
const validators: ((formData: any) => Promise<void>)[] = []
provide(validatorsKey, validators)
const validatingCount = ref(0)

const addOneValidate = () => {
  if (validatingCount.value === 0) {
    emit('update:validating', true)
  }
  validatingCount.value++
}

const reduceOneValidate = () => {
  validatingCount.value--
  if (validatingCount.value === 0) {
    emit('update:validating', false)
  }
}
const validate = () => {
  return new Promise<void>(resolve => {
    validators.forEach(validator => validator(innerValue.value))
    Promise.all(validators.map(validator => validator(innerValue.value))).then(
      () => {
        nextTick(() => {
          if (Object.values(errorStatus.value).every(({ error }) => !error)) {
            resolve()
          }
        })
      }
    )
  })
}

const clearAll = () => {
  errorStatus.value = props.items.reduce(
    (obj, { field }) => ({
      ...obj,
      [field]: {
        error: false,
        message: '',
      },
    }),
    {}
  )
}

defineExpose({
  validate,
  clearAll,
})
</script>
<template>
  <div
    :class="[
      'c-form',
      'c-row',
      'c-items-center',
      'c-wrap',
      `c-gutter-${gutterSize}`,
    ]"
  >
    <!-- 
      @slot The default content. This would override the config items generated content.
      @zh 默认插槽，会覆盖配置式生成的内容 -->
    <slot>
      <c-form-item
        v-for="item in items"
        :key="item.field"
        :label="item.label"
        :field="item.field"
        :col="item.col"
        :rules="item.rules"
        @validate-start="addOneValidate"
        @validate-end="reduceOneValidate"
      >
        <template
          #default="{ validate: validateCurrentItem, clearValidate, hasError }"
        >
          <!-- 
            @slot 
            @name [field] - 表单项的自定义内容，field为表单项的field属性
              @binding {Function} validate 当前表单项验证方法，调用立即触发当前表单项验证
              @binding {Function} clearValidate 当前表单项清除验证方法，调用立即清除当前表单项验证
              @binding {boolean} hasError 当前表单项是否有错误
          -->
          <slot
            :name="item.field"
            v-bind="{
              validate: () => validateCurrentItem(modelValue[item.field]),
              clearValidate,
              hasError,
            }"
          >
            <Component
              :is="getComponent(item.component)"
              v-model="innerValue[item.field]"
              v-bind="item.componentProps"
            />
          </slot>
        </template>
      </c-form-item>
    </slot>
  </div>
</template>
