// packages/react/ui/src/components/form/CRadioGroup.tsx
import React from 'react'
import clsx from 'clsx'
import { CSize } from 'casual-types'
import useGutterSize, { CGutterSizeContext } from '../../hooks/useGutterSize'
import useSize, { CSizeContext } from '../../hooks/useSize'
import CRadio from './CRadio'

interface CRadioGroupProps {
  /**
   * 当前选中值
   */
  value: any
  /**
   * 当前选中值变化时触发的回调
   */
  onChange?: (value: any) => void
  /**
   * 选项数组
   */
  options: { value: string | number; label: string }[]
  /**
   * 尺寸
   */
  size?: CSize
  /**
   * 选项间距
   */
  gutterSize?: CSize
}
const CRadioGroup = ({
  size,
  onChange,
  gutterSize,
  options = [],
  value,
}: CRadioGroupProps) => {
  const realGutterSize = useGutterSize(gutterSize)
  return (
    <CGutterSizeContext.Provider value={realGutterSize}>
      <CSizeContext.Provider value={useSize(size)}>
        <div
          className={clsx(
            'c-flex',
            'c-items-center',
            'c-wrap',
            `c-gutter-${realGutterSize}`
          )}
        >
          {options.map(option => (
            <CRadio
              key={option.value}
              value={value}
              onChange={onChange}
              selectedValue={option.value}
              label={option.label}
            />
          ))}
        </div>
      </CSizeContext.Provider>
    </CGutterSizeContext.Provider>
  )
}
export default CRadioGroup
export type { CRadioGroupProps }

// packages/vue/ui/src/components/form/CRadioGroup.vue
<script setup lang="ts">
import type { CSize } from 'casual-types'
import useFormProps from './useFormProps'

interface CRadioGroups {
  /**
   * 当前值，用于<code>v-model</code>绑定用
   */
  modelValue: boolean | string | number
  /**
   * 选项数组
   */
  options: { value: string | number; label: string }[]
  /**
   * 尺寸
   * @default 'md'
   */
  size?: CSize
  /**
   * 选项间距
   * @default 'md'
   */
  gutterSize?: CSize
}

const props = withDefaults(defineProps<CRadioGroups>(), {
  size: undefined,
  gutterSize: undefined,
})

defineEmits<{
  /**
   * 当前值变化时触发
   * @param newValue 新值
   */
  (e: 'update:modelValue', newValue: string | number): void
}>()

const { gutterSize } = useFormProps(props)
</script>
<template>
  <div class="c-flex c-items-center c-wrap" :class="[`c-gutter-${gutterSize}`]">
    <div v-for="{ label, value } in options" :key="value">
      <c-radio
        :model-value="modelValue"
        :label="label"
        :value="value"
        @update:model-value="$emit('update:modelValue', $event)"
      />
    </div>
  </div>
</template>
<style lang="scss" scoped></style>
