// packages/react/ui/src/components/form/CCheckbox.tsx
import { CSize, CTheme } from 'casual-types'
import { useSize, useTheme } from 'casual-ui-react'
import clsx from 'clsx'
import React from 'react'
import { useFormItemContext } from './CFormContext'
type CCheckboxModel = boolean | string | number

interface CCheckboxProps {
  /**
   * The color theme of checkbox
   * @zh 主题
   */
  theme?: CTheme
  /**
   * The size of checkbox
   * @zh 尺寸
   */
  size?: CSize
  /**
   * The label text
   * @zh 文字
   */
  label?: string
  /**
   * The current value
   * @zh 当前值
   */
  value: CCheckboxModel
  /**
   * Emit when the current value change
   * @zh 当前值变化时触发
   */
  onChange?: (newValue: CCheckboxModel) => void
  /**
   * The value used for checked
   * @zh 选中时的值
   */
  checkedValue?: CCheckboxModel
  /**
   * Determine whether the checkbox is disabled or not.
   * @zh 是否禁用
   */
  disabled?: boolean
}

const CCheckbox = ({
  value,
  checkedValue = true,
  onChange,
  theme,
  label = '',
  size,
  disabled = false,
}: CCheckboxProps) => {
  const toggleCheckStatus = () => {
    if (disabled) return
    onChange?.(value === checkedValue ? '' : checkedValue)
  }

  const realTheme = useTheme(theme)
  const realSize = useSize(size)

  const { hasError } = useFormItemContext()

  return (
    <div
      className={clsx(
        'c-checkbox',
        `c-checkbox--theme-${realTheme}`,
        `c-h-${realSize}`,
        `c-font-${realSize}`,
        checkedValue === value && 'c-checkbox--checked',
        disabled && 'c-checkbox--disabled',
        hasError && 'c-checkbox--has-error'
      )}
      onClick={toggleCheckStatus}
    >
      <svg
        className="c-checkbox--check-wrapper"
        viewBox="0 0 24 24"
        aria-hidden="true"
      >
        <path
          className="c-checkbox--checker"
          fill="none"
          d="M1.73,12.91 8.1,19.28 22.79,4.59"
        ></path>
        {/* <path d="M4,14H20V10H4"></path> */}
      </svg>
      <div className="c-checkbox--label">{label}</div>
    </div>
  )
}

export default CCheckbox

export type { CCheckboxProps, CCheckboxModel }

// packages/svelte/src/lib/components/form/CCheckbox.svelte
<script>
  import { useValidator } from '$lib/hooks/useForm'

  import useSize from '$lib/hooks/useSize'
  import bem from '$lib/utils/bem'
  import clsx from '$lib/utils/clsx'
  import { createEventDispatcher } from 'svelte'

  /**
   * Determine whether the checkbox is checked or not. It is recommended to use `bind:value`.
   * @type {boolean | string | number=}
   */
  export let value = undefined

  /**
   * The theme color
   * @type {'primary' | 'secondary' | 'warning' | 'negative'}
   */
  export let theme = 'primary'

  /**
   * The size of checkbox.
   * @type {'xs' | 'sm' | 'md' | 'lg' | 'xl'=}
   */
  export let size = void 0

  /**
   * The text label of checkbox.
   * @type {string}
   */
  export let label = ''

  /**
   * The checked value pass to `value` prop when the checkbox is checked.
   * @type {boolean | string | number}
   */
  export let checkedValue = true

  /**
   * Determine whether the checkbox is disabled or not.
   * @type {boolean}
   */
  export let disabled = false

  const dispatch = createEventDispatcher()

  $: contextSize = useSize(size)

  const { hasError } = useValidator()

  const onClick = () => {
    if (disabled) return
    const newValue = value === checkedValue ? void 0 : checkedValue
    value = newValue
    /**
     * Emit when the checked status change.
     */
    dispatch('change', newValue)
  }
</script>

<div
  class={clsx(
    bem('checkbox', {
      checked: value === checkedValue,
      disabled,
      hasError: $hasError,
    }),
    `c-checkbox--theme-${theme} c-h-${$contextSize} c-font-${$contextSize}`
  )}
  on:click={onClick}
>
  <svg class="c-checkbox--check-wrapper" viewBox="0 0 24 24" aria-hidden="true">
    <path
      class="c-checkbox--checker"
      fill="none"
      d="M1.73,12.91 8.1,19.28 22.79,4.59"
    />
    <!-- TODO: half checked -->
    <!-- <path d="M4,14H20V10H4"></path> -->
  </svg>
  <div class="c-checkbox--label">
    <!-- Customize some label content. Notice that this slot would override the `label` prop -->
    <slot name="label">
      {label}
    </slot>
  </div>
</div>
