// packages/react/ui/src/components/form/CRadio.tsx
import React from 'react'
import { CSize } from 'casual-types'
import { useSize } from 'casual-ui-react'
import clsx from 'clsx'
import { useFormItemContext } from './CFormContext'

type CRadioModel = boolean | string | number

interface CRadioProps {
  /**
   * The current value.
   * @zh 当前值
   */
  value: CRadioModel
  /**
   * Emit when the current value change.
   * @zh 值发生变化时触发
   */
  onChange?: (newValue: CRadioModel) => void
  /**
   * The value used for checked status.
   * @zh 选中时的值
   */
  selectedValue?: CRadioModel
  /**
   * The label text.
   * @zh 文字
   */
  label?: string
  /**
   * The size of radio.
   * @zh 尺寸
   */
  size?: CSize
  /**
   *  Determine whether the radio is disabled or not.
   * @zh 是否禁用
   */
  disabled?: boolean
}

const CRadio = ({
  label = '',
  size,
  value,
  selectedValue = true,
  onChange,
  disabled = false,
}: CRadioProps) => {
  const realSize = useSize(size)
  const { hasError } = useFormItemContext()
  return (
    <div
      className={clsx(
        'c-radio',
        `c-font-${realSize}`,
        `c-h-${size}`,
        `c-radio--size-${size}`,
        value === selectedValue && 'c-radio--selected',
        disabled && 'c-radio--disabled',
        hasError && 'c-radio--has-error'
      )}
      onClick={() => {
        if (disabled) return
        onChange?.(value === selectedValue ? '' : selectedValue)
      }}
    >
      <svg
        className="c-radio--circle-wrapper"
        viewBox="0 0 24 24"
        aria-hidden="true"
        fill="currentColor"
      >
        <path d="M12,22a10,10 0 0 1 -10,-10a10,10 0 0 1 10,-10a10,10 0 0 1 10,10a10,10 0 0 1 -10,10m0,-22a12,12 0 0 0 -12,12a12,12 0 0 0 12,12a12,12 0 0 0 12,-12a12,12 0 0 0 -12,-12"></path>
        <path
          className="c-radio--inner-circle"
          d="M12,6a6,6 0 0 0 -6,6a6,6 0 0 0 6,6a6,6 0 0 0 6,-6a6,6 0 0 0 -6,-6"
        ></path>
      </svg>
      <div className="c-radio--label">{label}</div>
    </div>
  )
}

export default CRadio

export type { CRadioProps, CRadioModel }

// packages/svelte/src/lib/components/form/CRadio.svelte
<script>
  import { useValidator } from '$lib/hooks/useForm'
  import useSize from '$lib/hooks/useSize'
  import clsx from '$lib/utils/clsx'
  import { createEventDispatcher } from 'svelte'

  /**
   * The radio selected status. It is recommended to use `bind:value`.
   * @type {boolean | string | number}
   */
  export let value = false

  /**
   * The selected value.
   * @type {boolean | string | number}
   */
  export let selectedValue = true

  /**
   * The label text.
   * @type {string}
   */
  export let label = ''

  /**
   * The size of radio. Notice that the default value is `'md'` instead of `undefined`
   * @type {'xs' | 'sm' | 'md' | 'lg' | 'xl'=}
   */
  export let size = undefined

  /**
   * Determine whether the radio is disabled or not.
   */
  export let disabled = false

  const contextSize = useSize(size)

  const { hasError, validateCurrent, clearCurrent } = useValidator()

  const dispatch = createEventDispatcher()

  const onClick = () => {
    if (disabled || value === selectedValue) return
    value = selectedValue
    dispatch('change')
  }
</script>

<div
  class={clsx(
    `c-radio c-font-${$contextSize} c-h-${$contextSize} c-radio--size-${$contextSize}`,
    value === selectedValue && 'c-radio--selected',
    disabled && 'c-radio--disabled',
    $hasError && 'c-radio--has-error'
  )}
  on:click={onClick}
>
  <svg
    class="c-radio--circle-wrapper"
    viewBox="0 0 24 24"
    aria-hidden="true"
    fill="currentColor"
  >
    <path
      d="M12,22a10,10 0 0 1 -10,-10a10,10 0 0 1 10,-10a10,10 0 0 1 10,10a10,10 0 0 1 -10,10m0,-22a12,12 0 0 0 -12,12a12,12 0 0 0 12,12a12,12 0 0 0 12,-12a12,12 0 0 0 -12,-12"
    />
    <path
      class="c-radio--inner-circle"
      d="M12,6a6,6 0 0 0 -6,6a6,6 0 0 0 6,6a6,6 0 0 0 6,-6a6,6 0 0 0 -6,-6"
    />
  </svg>
  <div class="c-radio--label">
    {label}
  </div>
</div>
