// packages/react/ui/src/components/form/date-picker/CDatePicker.tsx
import React, { useEffect, useMemo, useState } from 'react'
import clsx from 'clsx'
import { CSize } from 'casual-types'
import dayjs from 'dayjs'
import { useSize, CSizeContext } from 'casual-ui-react'
import CDropdown from '../../interact/CDropdown'
import CInput from '../CInput'
import CDatePanelHeader from './CDatePanelHeader'
import CDateGridPanel from './CDateGridPanel'
import CDatePanel from './CDatePanel'
import { CSSTransition, TransitionGroup } from 'react-transition-group'

type DateValue = Date | null
type Formatter = (origin: DateValue, format: string) => string
type Unit = 'day' | 'month' | 'year'

const getDisplayMonth = (month: number) => {
  const d = new Date()
  d.setMonth(month)
  return d.toLocaleDateString('en-US', { month: 'short' })
}

interface CDatePickerProps {
  /**
   * 单选时选中的日期值
   */
  value?: DateValue
  /**
   * 单选时选中日期变化时触发事件
   */
  onChange?: (value: DateValue) => void
  /**
   * 单选时选中日期格式化后的值
   */
  formattedValue?: string
  /**
   * 单选时选中日期格式化后的值变化时触发事件
   */
  onFormattedValueChange?: (formattedValue: string) => void
  /**
   * 日期段选择时选中的日期范围值
   */
  rangeValue?: [DateValue, DateValue]
  /**
   * 日期段选择时，选中的日期段格式化后的值
   */
  formattedRangeValue?: [string, string]
  /**
   * 日期段选择时，选中日期段变化时触发事件
   */
  onRangeChange?: (value: [DateValue, DateValue]) => void
  /**
   * 日期段选择时，选中日期段格式化后的值变化时触发事件，<a href="https://day.js.org/docs/en/display/format#list-of-all-available-formats" target="_blank">Dayjs</a>
   */
  onFormattedRangeChange?: (formattedValue: [string, string]) => void
  /**
   * 格式化模板字符串，详情参考
   */
  format?: string
  /**
   * 自定义格式化函数
   */
  formatter?: Formatter
  /**
   * 尺寸
   */
  size?: CSize
  /**
   * 是否在完成选择时自动收起下拉
   */
  hideOnSelect?: boolean
  /**
   * 预设文本
   */
  placeholder?: string
  /**
   * 是否禁用
   */
  disabled?: boolean
  /**
   * 选择单位
   */
  unit?: Unit
  /**
   * 是否为日期段选择
   */
  range?: boolean
}

const CDatePicker = ({
  value = null,
  onChange,
  formattedValue,
  onFormattedValueChange,
  rangeValue = [null, null],
  onRangeChange,
  formattedRangeValue,
  onFormattedRangeChange,
  format = 'YYYY-MM-DD',
  size,
  formatter = (v, f) => {
    if (!v) {
      return ''
    }
    return dayjs(v).format(f)
  },
  range = false,
  unit = 'day',
  hideOnSelect = true,
  disabled = false,
  placeholder,
}: CDatePickerProps) => {
  const now = new Date()

  const innerFormatter = (d: DateValue) => formatter(d, format)

  useEffect(() => {
    if (!value) return
    onFormattedValueChange?.(innerFormatter(value))
  }, [value])

  useEffect(() => {
    const [start, end] = rangeValue
    onFormattedRangeChange?.([innerFormatter(start), innerFormatter(end)])
  }, [rangeValue])

  const displayValue = useMemo(() => {
    if (range) {
      const [start, end] = formattedRangeValue || ['', '']
      if (!start && !end) return ''
      return `${start} - ${end}`
    }
    return formattedValue || ''
  }, [range, formattedValue, formattedRangeValue])
  const [showDrop, setShowDrop] = useState(false)
  const [year, setYear] = useState(value?.getFullYear() || now.getFullYear())
  const [month, setMonth] = useState(value?.getMonth() || now.getMonth())
  const [yearRange, setYearRange] = useState<[number, number]>([
    year,
    year + 11,
  ])
  const [innerUnit, setInnerUnit] = useState(unit)
  const onDateSet = () => {
    if (hideOnSelect) {
      setShowDrop(false)
    }
  }
  const [panelSwitchDirection, setPanelSwitchDirection] = useState<
    'forward' | 'backward'
  >('forward')
  const onUpdateUnit = (newUnit: Unit) => {
    if (newUnit === 'day') {
      setPanelSwitchDirection('forward')
    } else if (newUnit === 'year') {
      setPanelSwitchDirection('backward')
    } else {
      if (innerUnit === 'day') {
        setPanelSwitchDirection('backward')
      } else {
        setPanelSwitchDirection('forward')
      }
    }
    setInnerUnit?.(newUnit)
  }

  const onMonthSet = (newMonth: number) => {
    setMonth(newMonth)
    onChange?.(
      new Date(value?.getFullYear() || year, newMonth, value?.getDate() || 1)
    )
    if (unit === 'day') {
      onUpdateUnit('day')
      return
    }
    onDateSet()
  }

  const onYearSet = (newYear: number) => {
    setYear(newYear)
    onChange?.(
      new Date(newYear, value?.getMonth() || month, value?.getDate() || 1)
    )
    if (unit === 'year') {
      onDateSet()
      return
    }
    onUpdateUnit('month')
  }

  const contextSize = useSize(size)

  const isYearActive = yearNum => yearNum === value?.getFullYear()

  const isMonthActive = (monthNum: number) => {
    const d = new Date()
    d.setFullYear(year)
    d.setMonth(monthNum)
    return (
      d.getFullYear() === value?.getFullYear() &&
      d.getMonth() === value?.getMonth()
    )
  }

  return (
    <CSizeContext.Provider value={contextSize}>
      <div
        className={clsx(
          'c-date-picker',
          `c-date-picker--size-${contextSize}`,
          `c-font-${contextSize}`,
          disabled && 'c-date-picker--disabled'
        )}
      >
        <CDropdown
          value={showDrop}
          onChange={setShowDrop}
          widthWithinParent={false}
          disabled={disabled}
          dropContent={
            <>
              <CDatePanelHeader
                year={year}
                month={month}
                yearRange={yearRange}
                unit={innerUnit}
                onYearChange={setYear}
                onMonthChange={setMonth}
                onUnitChange={onUpdateUnit}
                onYearRangeChange={setYearRange}
                unitSwitchable={!range}
              />
              <TransitionGroup
                className={clsx(
                  'c-date-picker--panel-wrapper',
                  `c-px-${contextSize}`,
                  `c-pb-${contextSize}`
                )}
              >
                <CSSTransition
                  timeout={300}
                  key={innerUnit}
                  classNames={{
                    enterActive:
                      panelSwitchDirection === 'forward'
                        ? 'c-date-panel-enter-active'
                        : 'c-date-panel-reverse-enter-active',
                    exitActive:
                      panelSwitchDirection === 'forward'
                        ? 'c-date-panel-leave-active'
                        : 'c-date-panel-reverse-leave-active',
                  }}
                >
                  <>
                    {innerUnit === 'month' && (
                      <CDateGridPanel
                        items={Array(12)
                          .fill(0)
                          .map((_, i) => i)}
                        displayFormatter={getDisplayMonth}
                        isActive={isMonthActive}
                        onItemClick={onMonthSet}
                      />
                    )}
                    {innerUnit === 'year' && (
                      <CDateGridPanel
                        items={Array(yearRange[1] - yearRange[0] + 1)
                          .fill(0)
                          .map((_, i) => i + yearRange[0])}
                        displayFormatter={item => item + ''}
                        isActive={isYearActive}
                        onItemClick={onYearSet}
                      />
                    )}
                    {innerUnit === 'day' && (
                      <CDatePanel
                        {...{
                          value,
                          dateRange: rangeValue,
                          formattedDateRange: formattedRangeValue,
                          range,
                          year,
                          month,
                          onChange: v => {
                            onChange?.(v)
                            onDateSet()
                          },
                          onDateRangeChange: onRangeChange,
                        }}
                      />
                    )}
                  </>
                </CSSTransition>
              </TransitionGroup>
            </>
          }
        >
          <CInput
            value={displayValue}
            placeholder={placeholder}
            readonly
            disabled={disabled}
          />
        </CDropdown>
      </div>
    </CSizeContext.Provider>
  )
}
export default CDatePicker
export type { CDatePickerProps, Unit, DateValue, Formatter }

// packages/vue/ui/src/components/form/date-picker/CDatePicker.vue
<script setup lang="ts">
import dayjs from 'dayjs'
import {
  CIcon,
  CDatePanel,
  useVModel,
  useInjectSize,
  CInput,
  CDropdown,
  useDefaultVModel,
  CYearPanel,
  CMonthPanel,
  CDatePanelHeader,
} from 'casual-ui-vue'
import { toRefs, watch, ref, computed } from 'vue'
import { CSize } from 'casual-types'
import { matCalendarToday } from '@quasar/extras/material-icons'
import useUnit from './useUnit'

type Unit = 'year' | 'month' | 'day'

interface ODatePickerProps {
  /**
   * 当前选中值，用于<code>v-model</code>绑定
   */
  modelValue?: Date | null
  /**
   * 格式化后的值，用于<code>v-model:formattedValue</code>绑定
   */
  formattedValue?: string
  /**
   * 选择日期范围时的值，用于<code>v-model:dateRage</code>绑定
   */
  dateRange?: [Date | null, Date | null]
  /**
   * 格式化后的日期段值，用于<code>v-model:formattedDateRange</code>绑定
   */
  formattedDateRange?: [string, string]
  /**
   * 格式化模板，详情参考 <a href="https://day.js.org/docs/en/display/format#list-of-all-available-formats" target="_blank">Dayjs</a>
   */
  format?: string
  /**
   * 自定义格式化函数
   */
  formatter?: (origin: Date | null, format: string) => string
  /**
   * 尺寸
   */
  size?: CSize
  /**
   * 是否在选择后自动收起下拉
   */
  hideOnSelect?: boolean

  /**
   * 是否使用日期段选择
   */
  range?: boolean

  /**
   * 预设文本
   */
  placeholder?: string
  /**
   * 是否禁用
   */
  disabled?: boolean
  /**
   * 选择单位，可用于<code>v-model:unit</code>绑定
   */
  unit?: Unit
}

const props = withDefaults(defineProps<ODatePickerProps>(), {
  format: 'YYYY-MM-DD',
  formatter: (d, f) => {
    if (!d) return ''
    return dayjs(d).format(f)
  },
  size: undefined,
  hideOnSelect: true,
  formattedValue: '',
  dateRange: () => [null, null],
  formattedDateRange: () => ['', ''],
  modelValue: () => new Date(),
  range: false,
  placeholder: '',
  disabled: false,
  unit: 'day',
})

const innerFormatter = (d: Date | null) => props.formatter(d, props.format)

const { provideSize: size } = useInjectSize(props)

const { formattedValue, dateRange, formattedDateRange } = toRefs(props)

const emit = defineEmits<{
  /**
   * 当前选中值发生变化时触发
   */
  (e: 'update:modelValue', newValue: Date | null): void
  /**
   * 格式化后的值发生变化时触发
   */
  (e: 'update:formattedValue', newValue: string): void

  /**
   * 日期段绑定值变化时触发
   */
  (e: 'update:dateRange', newRange: [Date | null, Date | null]): void
  /**
   * 日期段格式化之后的值变化时触发
   */
  (
    e: 'update:formattedDateRange',
    newFormattedDateRange: [string, string]
  ): void
  /**
   * 单位变化时触发
   */
  (e: 'update:unit', newValue: Unit): void
}>()

const innerUnit = useUnit(emit, props)

const innerValue = useDefaultVModel(props, emit)

const { innerValue: innerFormattedValue } = useVModel(
  formattedValue,
  innerFormatter(innerValue.value),
  newValue => {
    emit('update:formattedValue', newValue)
  }
)

const { innerValue: innerRange } = useVModel<[Date | null, Date | null]>(
  dateRange,
  dateRange.value,
  newRange => {
    emit('update:dateRange', newRange)
  }
)

const { innerValue: innerFormattedRangeValue } = useVModel(
  formattedDateRange,
  formattedDateRange.value,
  newFormattedRange => {
    emit('update:formattedDateRange', newFormattedRange)
  }
)

// 侦听单选值更改后，改变格式化后的值
watch(innerValue, newDate => {
  innerFormattedValue.value = innerFormatter(newDate)
})

watch(innerRange, newRange => {
  const [start, end] = newRange
  innerFormattedRangeValue.value = [innerFormatter(start), innerFormatter(end)]
})

const show = ref(false)

// 输入框里展示的值
const displayValue = computed(() => {
  if (props.range) {
    const [start, end] = innerFormattedRangeValue.value
    if (!start && !end) return ''
    return `${start} - ${end}`
  }
  return innerFormattedValue.value
})

const year = ref(innerValue.value?.getFullYear() || new Date().getFullYear())
const month = ref(innerValue.value?.getMonth() || new Date().getMonth())
const yearRange = ref<[number, number]>([year.value, year.value + 11])
const transitionName = ref('c-date-panel')
const initialUnit = innerUnit.value
const onDateSet = () => {
  if (props.hideOnSelect) {
    show.value = false
  }
}
const onUpdateUnit = (newUnit: Unit) => {
  if (newUnit === 'day') {
    transitionName.value = 'c-date-panel'
  } else if (newUnit === 'year') {
    transitionName.value = 'c-date-panel-reverse'
  } else {
    if (innerUnit.value === 'day') {
      // day to month
      transitionName.value = 'c-date-panel-reverse'
    } else {
      // year to month
      transitionName.value = 'c-date-panel'
    }
  }
  innerUnit.value = newUnit
}
const onMonthSet = (newDate: Date | null) => {
  month.value = newDate?.getMonth() || 0
  if (initialUnit === 'day') {
    onUpdateUnit('day')
    return
  }
  onDateSet()
}

const onYearSet = (newDate: Date | null) => {
  year.value = newDate?.getFullYear() || 0
  if (initialUnit === 'year') {
    onDateSet()
    return
  }
  onUpdateUnit('month')
}
</script>
<template>
  <div
    :class="[
      'c-date-picker',
      `c-font-${size}`,
      `c-date-picker--size-${size}`,
      { 'c-date-picker--disabled': disabled },
    ]"
  >
    <c-dropdown
      v-model="show"
      :width-within-parent="false"
      :disabled="disabled"
    >
      <c-input
        :model-value="displayValue"
        readonly
        :placeholder="placeholder"
        :disabled="disabled"
        clearable
        @clear="
          () => {
            innerValue = null
            innerRange = [null, null]
          }
        "
      >
        <template #suffix>
          <c-icon :content="matCalendarToday" />
        </template>
      </c-input>
      <template #drop-content>
        <c-date-panel-header
          v-model:year="year"
          v-model:month="month"
          v-model:yearRange="yearRange"
          :unit="innerUnit"
          :unit-switchable="!range"
          @update:unit="onUpdateUnit"
        />
        <div
          class="c-date-picker--panel-wrapper"
          :class="[`c-px-${size}`, `c-pb-${size}`]"
        >
          <transition-group :name="transitionName">
            <c-date-panel
              v-if="innerUnit === 'day'"
              key="day"
              v-model="innerValue"
              v-model:dateRange="innerRange"
              :formatted-date-range="innerFormattedRangeValue"
              :range="range"
              :year="year"
              :month="month"
              @update:model-value="onDateSet"
            />
            <c-month-panel
              v-else-if="innerUnit === 'month'"
              key="month"
              v-model="innerValue"
              :year="year"
              @update:model-value="onMonthSet"
            />
            <c-year-panel
              v-else-if="innerUnit === 'year'"
              key="year"
              v-model="innerValue"
              :year-range="yearRange"
              @update:model-value="onYearSet"
            />
          </transition-group>
        </div>
      </template>
    </c-dropdown>
  </div>
</template>
