// packages/vue/ui/src/components/table/CTable.vue
<script setup lang="ts">
import { provide } from 'vue'
import CTr from './CTr.vue'
import CTd from './CTd.vue'
import CTh from './CTh.vue'

interface TableColumn {
  title: string
  field: string
  width?: string
}
interface TableProps {
  /**
   * 是否为条纹表格
   */
  striped?: boolean
  /**
   * 表格列配置
   */
  columns?: TableColumn[]
  /**
   * 表格数据
   */
  data?: Array<Record<string, string | number>>
  /**
   * 行数据唯一键
   */
  rowKey?: string
}

const props = withDefaults(defineProps<TableProps>(), {
  columns: () => [],
  data: () => [],
  rowKey: 'id',
  striped: false,
})

provide('columns', props.columns)
</script>
<template>
  <div class="c-table" :class="[{ 'c-table--striped': striped }]">
    <table class="c-table--table">
      <colgroup>
        <col v-for="{ field } in columns" :key="field" />
      </colgroup>
      <thead>
        <c-tr>
          <c-th
            v-for="{ field, title, width } in columns"
            :key="field"
            :width="width"
          >
            <slot :name="`th-${field}`" v-bind="{ field, title }">
              {{ title }}
            </slot>
          </c-th>
        </c-tr>
      </thead>
      <tbody>
        <c-tr v-for="row in data" :key="row[rowKey]">
          <c-td v-for="({ field, width }, idx) in columns" :key="field">
            <slot
              :name="`td-${field}`"
              :width="width"
              v-bind="{ field, val: row[field], idx, row }"
            >
              {{ row[field] }}
            </slot>
          </c-td>
        </c-tr>
      </tbody>
    </table>
    <div v-if="data.length === 0" class="c-table--no-data">No Data</div>
  </div>
</template>

// packages/react/ui/src/components/table/CTable.tsx
import clsx from 'clsx'
import React from 'react'
import CTd from './CTd'
import CTh from './CTh'
import CTr from './CTr'

interface CustomRenderProps<T = any> {
  idx?: number
  val?: T
  field: string | number | symbol
  row: T
}

interface CustomHeaderRenderProps {
  title: string
  field: string | number | symbol
}

type CustomHeaderRender = (
  props: CustomHeaderRenderProps
) => JSX.Element | string

type CustomRender = (props: CustomRenderProps) => JSX.Element | string

interface CTableColumn<T = any, S extends keyof T = any> {
  /**
   * 列标题
   */
  title: string
  /**
   * 列对应字段名
   */
  field: S
  /**
   * 自定义单元格渲染
   */
  customRender?: CustomRender
  /**
   * 自定义表头渲染
   */
  customHeader?: CustomHeaderRender
  /**
   * 列宽
   */
  width?: string
}
interface CTableProps<
  T extends Record<string | number | symbol, any>,
  S extends keyof T
> {
  /**
   * 是否为条纹表格
   */
  striped?: boolean
  /**
   * 表格列配置
   */
  columns?: CTableColumn<T, S>[]
  /**
   * 表格数据
   */
  data?: Array<T>
  /**
   * 行数据唯一键
   */
  rowKey?: string
}

function CTable<T>({
  striped = false,
  columns = [],
  data = [],
  rowKey = 'id',
}: CTableProps<T, keyof T>) {
  return (
    <div className={clsx('c-table', striped && 'c-table--striped')}>
      <table className="c-table--table">
        <colgroup>
          {columns.map(({ field }) => (
            <col key={String(field)}></col>
          ))}
        </colgroup>
        <thead>
          <CTr>
            {columns.map(({ field, title, customHeader, width }) => (
              <CTh key={String(field)} width={width}>
                {customHeader
                  ? customHeader({
                      field,
                      title,
                    })
                  : title}
              </CTh>
            ))}
          </CTr>
        </thead>
        <tbody>
          {data.map((row, idx) => (
            <CTr key={row[rowKey]}>
              {columns.map(({ field, customRender, width }) => (
                <CTd key={String(field)} width={width}>
                  {customRender
                    ? customRender({
                        row,
                        val: row[field],
                        idx,
                        field,
                      })
                    : String(row[field])}
                </CTd>
              ))}
            </CTr>
          ))}
        </tbody>
      </table>
      {data.length === 0 && <div className="c-table--no-data">No Data</div>}
    </div>
  )
}

export type { CTableProps, CTableColumn, CustomRender, CustomRenderProps }

export default CTable
