// packages/vue/ui/src/components/carousel/CCarousel.vue
<script lang="ts">
export const slidesKey = Symbol('slides')
export const activeIndexKey = Symbol('activeIndex')
export const directionKey = Symbol('direction')
export const verticalKey = Symbol('vertical')
export const intervalKey = Symbol('interval')
export const timeoutKey = Symbol('timeout')
export const toNextKey = Symbol('toNext')

export type Direction = 'forward' | 'backward'
</script>
<script
  setup
  lang="ts"
>
import { computed, nextTick, provide, ref, toRefs } from 'vue'
import CButton from '../basic/button/CButton.vue'
import CIcon from '../basic/icon/CIcon.vue'
import {
  outlinedNavigateBefore,
  outlinedNavigateNext,
} from '@quasar/extras/material-icons-outlined'

interface Props {
  /**
   * The current active index (from 0). Can used with <code>v-model</code>
   * @zh 当前激活项下标，可使用<code>v-model</code>绑定
   */
  modelValue?: number
  /**
   * The height of container.
   * @zh 轮播容器高度
   */
  height?: string
  /**
   * The theme color. It will affect the indicators and controls' color.
   * @zh 轮播主题，该值会指示器以及箭头控制器主题色
   */
  theme?: 'primary' | 'secondary' | 'warning' | 'negative'
  /**
   * The autoplay interval. If set to a value larger than 0. Autoplay will be set.
   * @zh 自动播放时间间隔，单位为毫秒. 设置大于0时会开启自动播放
   */
  interval?: number
  /**
   * The indicators' horizontal position.
   * @zh 指示器水平方向的位置
   */
  indicatorsPositionHorizontal?: 'start' | 'center' | 'end'
  /**
   * The indicators' vertical position.
   * @zh 指示器垂直方向的位置
   */
  indicatorsPositionVertical?: 'start' | 'center' | 'end'
  /**
   * The indicators align direction.
   * @zh 指示器排列方式
   */
  indicatorsAlignDirection?: 'row' | 'column' | 'row-reverse' | 'column-reverse'
  /**
   * Determine whether the transition is vertical or not.
   * @zh 是否为纵向过渡
   */
  vertical?: boolean
  /**
   * Determine whether the sliders can be toggled infinity or not.
   * @zh 是否为循环播放
   */
  infinity?: boolean
  /**
   * The arrow control shown timing.
   * @zh 箭头控制器展示时机
   */
  arrowTiming?: 'always' | 'hover' | 'never'
}
const props = withDefaults(defineProps<Props>(), {
  modelValue: 0,
  height: '300px',
  theme: 'primary',
  interval: 0,
  indicatorsPositionHorizontal: 'center',
  indicatorsPositionVertical: 'end',
  indicatorsAlignDirection: 'row',
  vertical: false,
  infinity: false,
  arrowTiming: 'always',
})
const emit = defineEmits<{
  (e: 'update:modelValue', newIndex: number): void
}>()
const slides = ref([])
const direction = ref<Direction>('forward')
const timeoutFlag = ref(null)

const { modelValue, vertical, interval } = toRefs(props)

provide(slidesKey, slides)
provide(activeIndexKey, modelValue)
provide(directionKey, direction)
provide(verticalKey, vertical)
provide(intervalKey, interval)
provide(timeoutKey, timeoutFlag)

const showArrow = ref(props.arrowTiming === 'always')

const onContainerMouseEnter = () => {
  if (props.arrowTiming === 'hover') {
    showArrow.value = true
  }
}
const onContainerMouseLeave = () => {
  if (props.arrowTiming === 'hover') {
    showArrow.value = false
  }
}

const toIndex = (idx: number) => {
  const updateIndex = (i: number) => {
    nextTick(() => {
      emit('update:modelValue', i)
    })
  }
  if (idx < props.modelValue) {
    if (idx >= 0) {
      direction.value = 'backward'
      updateIndex(idx)
      return
    }
    if (props.infinity) {
      direction.value = 'backward'
      updateIndex(slides.value.length - 1)
    }
    return
  }
  if (idx > props.modelValue) {
    if (idx < slides.value.length) {
      direction.value = 'forward'
      updateIndex(idx)
      return
    }
    if (props.infinity) {
      direction.value = 'forward'
      updateIndex(0)
    }
  }
}
const toPrev = () => toIndex(props.modelValue - 1)
const toNext = () => toIndex(props.modelValue + 1)

const showPrev = computed(
  () => showArrow.value && (props.infinity || props.modelValue > 0)
)
const showNext = computed(
  () =>
    showArrow.value &&
    (props.infinity || props.modelValue < slides.value.length - 1)
)

provide(toNextKey, toNext)

defineExpose({
  toIndex,
  toPrev,
  toNext,
})
</script>
<template>
  <div
    :class="['c-carousel', { 'c-carousel--vertical': vertical }]"
    :style="{
      height,
    }"
    @mouseenter="onContainerMouseEnter"
    @mouseleave="onContainerMouseLeave"
  >
    <div
      :class="[
        'c-carousel--indicators',
        'c-flex',
        `c-items-${indicatorsPositionVertical}`,
        `c-justify-${indicatorsPositionHorizontal}`,
      ]"
    >
      <div
        :class="[
          'c-carousel--indicators-container',
          'c-gutter-sm',
          'c-flex',
          `c-${indicatorsAlignDirection}`,
        ]"
      >
        <!-- 
          @slot Customize the indicators content. 
          @zh 自定义指示器内容 
        -->
        <slot name="indicators">
          <div
            v-for="(_, i) in slides"
            :key="i"
          >
            <div
              :class="[
                'c-carousel--indicator-item',
                `c-carousel--indicator-item--${theme}`,
                { 'c-carousel--indicator-item--active': i === modelValue },
              ]"
              @click="toIndex(i)"
            ></div>
          </div>
        </slot>
      </div>
    </div>

    <Transition name="c-carousel-control">
      <div
        v-if="showPrev"
        class="c-carousel--control c-carousel--control--prev"
        @click="toPrev"
      >
        <!-- 
          @slot Customize the to previous control arrow. 
          @zh 自定义向前箭头控制器内容 
        -->
        <slot name="control-prev">
          <c-button
            icon
            flat
            :theme="theme"
          >
            <c-icon :content="outlinedNavigateBefore" />
          </c-button>
        </slot>
      </div>
    </Transition>

    <Transition name="c-carousel-control">
      <div
        v-if="showNext"
        class="c-carousel--control c-carousel--control--next"
        @click="toNext"
      >
        <!-- 
          @slot Customize the to next control arrow. 
          @zh 自定义向后箭头控制器内容 
        -->
        <slot name="control-next">
          <c-button
            icon
            flat
            :theme="theme"
          >
            <c-icon :content="outlinedNavigateNext" />
          </c-button>
        </slot>
      </div>
    </Transition>

    <div class="c-carousel--sliders">
      <!-- 
        @slot The content of carousel. It is recommended to use <code>c-carousel-slider</code>.
        @zh 轮播内容，推荐使用<code>c-carousel-slider</code>
      -->
      <slot />
    </div>
  </div>
</template>

// packages/svelte/src/lib/components/carousel/CCarousel.svelte
<script context="module">
  /**
   * Records the names of this carousel.
   */
  export const slidesKey = Symbol('c-carousel-names')

  /**
   * The current index.
   */
  export const activeIndexKey = Symbol('c-carousel-active-index')

  /**
   * The move direction. Can be `'forward'` or `'backward'`
   */
  export const directionKey = Symbol('c-carousel-direction')

  /**
   * The vertical context. Determine whether the carousel moving vertical.
   */
  export const verticalKey = Symbol('c-carousel-vertical')

  /**
   * The auto play interval key.
   */
  export const intervalKey = Symbol('c-carousel-interval')

  /**
   * To next function key.
   */
  export const toNextKey = Symbol('c-carousel-to-next')

  /**
   * The timeout flag key.
   */
  export const timeoutKey = Symbol('c-carousel-timeout-flag')
</script>

<script>
  import bem from '$lib/utils/bem'
  import clsx from '$lib/utils/clsx'
  import { setContext } from 'svelte'
  import { cubicInOut } from 'svelte/easing'
  import { writable } from 'svelte/store'
  import { fade } from 'svelte/transition'
  import CButton from '../CButton.svelte'

  /**
   * The container height.
   * @type {string}
   */
  export let height = '300px'

  /**
   * The theme of indicators and arrow controls.
   * @type {'primary' | 'secondary' | 'warning' | 'negative'}
   */
  export let theme = 'primary'

  /**
   * The auto play interval. If it set to a value less than 0. The auto play will be disabled.
   * @type {number}
   */
  export let interval = 0

  /**
   * The current active slider index (from 0). You can use `bind:activeIndex`.
   * @type {number}
   */
  export let activeIndex = 0

  /**
   * Determine the indicators horizontal position.
   * @type {'start' | 'center' | 'end'}
   */
  export let indicatorsPositionHorizontal = 'center'

  /**
   * Determine the indicators vertical position.
   * @type {'start' | 'center' | 'end'}
   */
  export let indicatorsPositionVertical = 'end'

  /**
   * Determine the idicators align direction.
   *
   * This prop use [CSS `flex-direction`](https://developer.mozilla.org/en-US/docs/Web/CSS/flex-direction).
   * @type {'row' | 'row-reverse' | 'column' | 'column-reverse'}
   */
  export let indicatorsAlignDirection = 'row'

  /**
   * Determine whether the transition direction is vertical or not.
   * @type {boolean}
   */
  export let vertical = false

  /**
   * Determine whether the sliders can be infinity loop.
   * @type {boolean}
   */
  export let infinity = false

  /**
   * Determine the arrow controls shown timing.
   * @type {'always' | 'hover' | 'never'}
   */
  export let arrowTiming = 'always'

  const direction = writable('forward')

  const slides = writable([])

  const activeIndexStore = writable(activeIndex)

  const verticalContext = writable(vertical)

  const intervalContext = writable(interval)

  const timeoutFlag = writable(null)

  setContext(slidesKey, slides)
  setContext(activeIndexKey, activeIndexStore)
  setContext(directionKey, direction)
  setContext(verticalKey, verticalContext)
  setContext(intervalKey, intervalContext)
  setContext(timeoutKey, timeoutFlag)

  /**
   * Goto specific slider
   * @param {number} idx
   */
  const toIndex = idx => {
    if (idx < activeIndex) {
      if (idx >= 0) {
        $direction = 'backward'
        activeIndex = idx
        return
      }
      if (infinity) {
        $direction = 'backward'
        activeIndex = $slides.length - 1
      }
      return
    }
    if (idx > activeIndex) {
      if (idx < $slides.length) {
        $direction = 'forward'
        activeIndex = idx
        return
      }
      if (infinity) {
        $direction = 'forward'
        activeIndex = 0
      }
    }
  }

  /**
   * Go to previous slide. If current is the first slide and `infinity` is `true`. Will goto the last slide.
   */
  const toPrev = () => toIndex(activeIndex - 1)

  /**
   * Go to previous slide. If current is the last and `infinity` is `true`. Will goto the first slide.
   */
  const toNext = () => toIndex(activeIndex + 1)

  let showArrow = arrowTiming === 'always'

  const onContainerMouseEnter = () => {
    if (arrowTiming === 'hover') {
      showArrow = true
    }
  }

  const onContainerMouseLeave = () => {
    if (arrowTiming === 'hover') {
      showArrow = false
    }
  }

  setContext(toNextKey, toNext)

  $: {
    $activeIndexStore = activeIndex
  }

  $: {
    $verticalContext = vertical
  }

  export { toPrev, toNext, toIndex }
</script>

<div
  class={bem('carousel', {
    vertical,
  })}
  style={`height: ${height}`}
  on:mouseenter={onContainerMouseEnter}
  on:mouseleave={onContainerMouseLeave}
>
  <div
    class={`c-carousel--indicators c-flex c-items-${indicatorsPositionVertical} c-justify-${indicatorsPositionHorizontal}`}
  >
    <div
      class={`c-carousel--indicators-container c-gutter-sm c-flex c-${indicatorsAlignDirection}`}
    >
      <!--
        Customize the indicators content.

        @param {string[]} names The names array of this carousel.
      -->
      <slot name="indicators">
        {#each $slides as _, i}
          <div>
            <div
              class={clsx(
                `c-carousel--indicator-item`,
                `c-carousel--indicator-item--${theme}`,
                i === activeIndex && 'c-carousel--indicator-item--active'
              )}
              on:click={() => toIndex(i)}
            />
          </div>
        {/each}
      </slot>
    </div>
  </div>

  {#if showArrow && (infinity || activeIndex > 0)}
    <div
      class="c-carousel--control c-carousel--control--prev"
      transition:fade={{ duration: 300, easing: cubicInOut }}
      on:click={toPrev}
    >
      <!-- Customize the to previous slide control content -->
      <slot name="control-prev">
        <CButton icon flat {theme}>
          <div i-ooui-previous-ltr />
        </CButton>
      </slot>
    </div>
  {/if}

  {#if showArrow && (infinity || activeIndex < $slides.length - 1)}
    <div
      class="c-carousel--control c-carousel--control--next"
      transition:fade={{ duration: 300, easing: cubicInOut }}
      on:click={toNext}
    >
      <!-- Customize the to next slide control content -->
      <slot name="control-next">
        <CButton icon flat {theme}>
          <div i-ooui-previous-rtl />
        </CButton>
      </slot>
    </div>
  {/if}

  <div class="c-carousel--sliders">
    <!-- The slides content. It is recommended to use [CCarouselSlider](/components/carousel-slider) -->
    <slot />
  </div>
</div>
