// packages/react/ui/src/components/carousel/CCarousel.tsx
import {
  matNavigateBefore,
  matNavigateNext,
} from '@quasar/extras/material-icons'
import { CSlot, CTheme } from 'casual-types'
import clsx from 'clsx'
import React, { useCallback, useMemo, useState, useEffect } from 'react'
import CButton from '../basic/button/CButton'
import CIcon from '../basic/icon/CIcon'
import Fade from '../transition/Fade'
import TransitionWrapper from './TransitionWrapper'
import { CarouselContext } from './CarouselContext'
interface CCarouselProps {
  /**
   * The height of container.
   * @zh 容器的高度
   */
  height?: string

  /**
   * The theme color. It will affect the control arrow and the indicators' style.
   * @zh 主题色，会影响指示器以及箭头控制器的颜色
   */
  theme?: CTheme

  /**
   * The autoplay interval. If the value is larger than 0 will set a autoplay. Notice that the transition time is not counting.
   * @zh 自动播放间隔，若该值大于0会以该值启动自动播放。值得一提的是动画过渡时间并不会算在内
   */
  interval?: number

  /**
   * The current slider index (from 0).
   * @zh 当前激活的轮播下标（从0开始）
   */
  activeIndex?: number

  /**
   * Emit when the current slider index changed.
   * @zh 当前激活的轮播变化时触发
   */
  onActiveIndexChange?: (newIndex: number) => void

  /**
   * The horizontal position of the indicators.
   * @zh 指示器的横向位置
   */
  indicatorsPositionHorizontal?: 'start' | 'center' | 'end'

  /**
   * The vertical position of the indicators.
   * @zh 指示器的纵向位置
   */
  indicatorsPositionVertical?: 'start' | 'center' | 'end'

  /**
   * The align direction of indicators.
   * @zh 指示器排列方向
   */
  indicatorsAlignDirection?: 'row' | 'row-reverse' | 'column' | 'column-reverse'

  /**
   * Determine whether the transition is vertical or not.
   * @zh 是否纵向过渡
   */
  vertical?: boolean

  /**
   * Determine the carousel can be infinity or not.
   * @zh 是否无限循环
   */
  infinity?: boolean

  /**
   * Determine the arrow shown method.
   * @zh 箭头展示时机
   */
  arrowTiming?: 'always' | 'hover' | 'never'

  /**
   * Customize the indicators content.
   * @zh 自定义指示器内容
   */
  customIndicators?: CSlot

  /**
   * Customize the to previous control arrow.
   * @zh 自定义前一个箭头控制器
   */
  customArrowPrev?: CSlot

  /**
   * Customize the to next control arrow.
   * @zh 自定义后一个箭头控制器
   */
  customArrowNext?: CSlot

  /**
   * Determine whether to pause the autoplay when the carousel is hovered.
   * @zh 鼠标悬浮时是否暂停自动播放
   */
  pauseOnHover?: boolean

  /**
   * The content of carousel. It is recommended to use `CCarouselSlider`
   * @zh 内容，建议使用<code>CCarouselSlider</code>
   */
  children: any[]
}

type Direction = 'forward' | 'backward'

const CCarousel = ({
  height = '300px',
  theme = 'primary',
  interval = 0,
  activeIndex = 0,
  onActiveIndexChange,
  indicatorsAlignDirection = 'row',
  indicatorsPositionHorizontal = 'center',
  indicatorsPositionVertical = 'end',
  vertical = false,
  infinity = false,
  arrowTiming = 'always',
  customIndicators,
  customArrowPrev,
  customArrowNext,
  children,
  pauseOnHover = true,
}: CCarouselProps) => {
  const [direction, setDirection] = useState<Direction>('forward')

  const [showArrow, setShowArrow] = useState(arrowTiming === 'always')

  const showPrevArrow = useMemo(
    () => showArrow && (infinity || activeIndex > 0),
    [showArrow, infinity, activeIndex]
  )

  const showNextArrow = useMemo(
    () => showArrow && (infinity || activeIndex < children.length - 1),
    [showArrow, infinity, activeIndex]
  )

  const [hovering, setHovering] = useState(false)

  const pauses: Function[] = []
  const resumes: Function[] = []

  const onMouseEnter = () => {
    if (arrowTiming === 'hover') {
      setShowArrow(true)
    }
    setHovering(true)
    if (pauseOnHover) {
      pauses.forEach(p => p())
    }
  }

  const onMouseLeave = () => {
    if (arrowTiming === 'hover') {
      setShowArrow(false)
    }
    setHovering(false)
    if (pauseOnHover) {
      resumes.forEach(r => r())
    }
  }

  const toIndex = useCallback(
    (idx: number) => {
      if (idx < activeIndex) {
        setDirection('backward')
        if (idx >= 0) {
          onActiveIndexChange?.(idx)
          return
        }
        if (infinity) {
          onActiveIndexChange?.(children.length - 1)
        }
        return
      }
      if (idx > activeIndex) {
        setDirection('forward')
        if (idx < children.length) {
          onActiveIndexChange?.(idx)
          return
        }
        if (infinity) {
          onActiveIndexChange?.(0)
        }
      }
    },
    [activeIndex, infinity]
  )

  const toPrev = useCallback(() => toIndex(activeIndex - 1), [activeIndex])

  const toNext = useCallback(() => toIndex(activeIndex + 1), [activeIndex])

  const [transitioning, setTransitioning] = useState(false)

  const indicatorAnimationState = useMemo<'running' | 'paused'>(
    () => ((pauseOnHover && hovering) || transitioning ? 'paused' : 'running'),
    [pauseOnHover, hovering, transitioning]
  )
  return (
    <CarouselContext.Provider
      value={{
        hovering,
        setSliding: setTransitioning,
        pauses,
        resumes,
      }}
    >
      <div
        className={clsx('c-carousel', vertical && 'c-carousel--vertical')}
        style={{
          height,
        }}
        onMouseEnter={onMouseEnter}
        onMouseLeave={onMouseLeave}
      >
        Hovering{hovering ? 'true' : 'false'}
        <div
          className={clsx(
            'c-carousel--indicators',
            'c-flex',
            `c-items-${indicatorsPositionVertical}`,
            `c-justify-${indicatorsPositionHorizontal}`
          )}
        >
          <div
            className={clsx(
              'c-carousel--indicators-container',
              'c-gutter-xs',
              'c-flex',
              `c-${indicatorsAlignDirection}`
            )}
          >
            {customIndicators
              ? customIndicators
              : children.map((_, i) => {
                  const isActive = i === activeIndex
                  return (
                    <div key={`indicators-${i}`}>
                      <div
                        className={clsx(
                          'c-carousel--indicator-item',
                          `c-carousel--indicator-item--${theme}`,
                          isActive && 'c-carousel--indicator-item--active'
                        )}
                        onClick={() => toIndex(i)}
                      >
                        <div className="c-carousel--indicator-item--bg"></div>
                        <div
                          className="c-carousel--indicator-item--progress-bar"
                          style={
                            isActive
                              ? {
                                  animationPlayState: indicatorAnimationState,
                                  animationName: `c-carousel-active-indicator-bar${
                                    indicatorsAlignDirection.startsWith('col')
                                      ? '-vertical'
                                      : ''
                                  }`,
                                  animationDuration: `${interval}ms`,
                                  animationIterationCount: 1,
                                }
                              : {}
                          }
                        ></div>
                      </div>
                    </div>
                  )
                })}
          </div>
        </div>
        <Fade show={showPrevArrow}>
          <div
            className="c-carousel--control c-carousel--control--prev"
            onClick={toPrev}
          >
            {customArrowPrev ? (
              customArrowPrev
            ) : (
              <CButton
                flat
                icon
                theme={theme}
              >
                <CIcon content={matNavigateBefore} />
              </CButton>
            )}
          </div>
        </Fade>
        <Fade show={showNextArrow}>
          <div
            className="c-carousel--control c-carousel--control--next"
            onClick={toNext}
          >
            {customArrowNext ? (
              customArrowNext
            ) : (
              <CButton
                flat
                icon
                theme={theme}
              >
                <CIcon content={matNavigateNext} />
              </CButton>
            )}
          </div>
        </Fade>
        <div className="c-carousel--sliders">
          {children.map((c, i) => (
            <TransitionWrapper
              key={i}
              children={c}
              direction={direction}
              activeIndex={activeIndex}
              currentIndex={i}
              toNext={toNext}
              interval={interval}
              vertical={vertical}
            />
          ))}
        </div>
      </div>
    </CarouselContext.Provider>
  )
}

export { CCarouselProps }

export default CCarousel

// packages/vue/ui/src/components/carousel/CCarousel.vue
<script lang="ts">
export const slidesKey = Symbol('slides')
export const activeIndexKey = Symbol('activeIndex')
export const directionKey = Symbol('direction')
export const verticalKey = Symbol('vertical')
export const intervalKey = Symbol('interval')
export const timeoutKey = Symbol('timeout')
export const toNextKey = Symbol('toNext')
export const slidingKey = Symbol('sliding')
export const hoveringKey = Symbol('hovering')
export const pauseFunctionsKey = Symbol('pauses')
export const resumeFunctionsKey = Symbol('resumes')

export type Direction = 'forward' | 'backward'
</script>
<script
  setup
  lang="ts"
>
import { computed, nextTick, onMounted, provide, ref, toRefs } from 'vue'
import CButton from '../basic/button/CButton.vue'
import CIcon from '../basic/icon/CIcon.vue'
import {
  outlinedNavigateBefore,
  outlinedNavigateNext,
} from '@quasar/extras/material-icons-outlined'

interface Props {
  /**
   * The current active index (from 0). Can used with <code>v-model</code>
   * @zh 当前激活项下标，可使用<code>v-model</code>绑定
   */
  modelValue?: number
  /**
   * The height of container.
   * @zh 轮播容器高度
   */
  height?: string
  /**
   * The theme color. It will affect the indicators and controls' color.
   * @zh 轮播主题，该值会指示器以及箭头控制器主题色
   */
  theme?: 'primary' | 'secondary' | 'warning' | 'negative'
  /**
   * The autoplay interval. If set to a value larger than 0. Autoplay will be set.
   * @zh 自动播放时间间隔，单位为毫秒. 设置大于0时会开启自动播放
   */
  interval?: number
  /**
   * The indicators' horizontal position.
   * @zh 指示器水平方向的位置
   */
  indicatorsPositionHorizontal?: 'start' | 'center' | 'end'
  /**
   * The indicators' vertical position.
   * @zh 指示器垂直方向的位置
   */
  indicatorsPositionVertical?: 'start' | 'center' | 'end'
  /**
   * The indicators align direction.
   * @zh 指示器排列方式
   */
  indicatorsAlignDirection?: 'row' | 'column' | 'row-reverse' | 'column-reverse'
  /**
   * Determine whether the transition is vertical or not.
   * @zh 是否为纵向过渡
   */
  vertical?: boolean
  /**
   * Determine whether the sliders can be toggled infinity or not.
   * @zh 是否为循环播放
   */
  infinity?: boolean
  /**
   * The arrow control shown timing.
   * @zh 箭头控制器展示时机
   */
  arrowTiming?: 'always' | 'hover' | 'never'
  /**
   * Determine whether to pause transition count down when the slider is hovered.
   * @zh 是否在鼠标悬停时暂停过渡倒计时
   */
  pauseOnHover?: boolean
}
const props = withDefaults(defineProps<Props>(), {
  modelValue: 0,
  height: '300px',
  theme: 'primary',
  interval: 0,
  indicatorsPositionHorizontal: 'center',
  indicatorsPositionVertical: 'end',
  indicatorsAlignDirection: 'row',
  vertical: false,
  infinity: false,
  arrowTiming: 'always',
  pauseOnHover: true,
})
const emit = defineEmits<{
  (e: 'update:modelValue', newIndex: number): void
}>()
const slides = ref([])
const direction = ref<Direction>('forward')
const timeoutFlag = ref(null)

const { modelValue, vertical, interval, pauseOnHover } = toRefs(props)

const pauses: Array<() => void> = []
const resumes: Array<() => void> = []

provide(slidesKey, slides)
provide(activeIndexKey, modelValue)
provide(directionKey, direction)
provide(verticalKey, vertical)
provide(intervalKey, interval)
provide(timeoutKey, timeoutFlag)
provide(pauseFunctionsKey, pauses)
provide(resumeFunctionsKey, resumes)

const showArrow = ref(props.arrowTiming === 'always')

const hovering = ref(false)
const sliding = ref(false)

provide(slidingKey, sliding)
provide(hoveringKey, hovering)

const onContainerMouseEnter = () => {
  hovering.value = true
  if (props.arrowTiming === 'hover') {
    showArrow.value = true
  }
  if (props.pauseOnHover) {
    pauses.forEach(p => p())
  }
}
const onContainerMouseLeave = () => {
  hovering.value = false

  if (props.arrowTiming === 'hover') {
    showArrow.value = false
  }
  if (props.pauseOnHover) {
    resumes.forEach(r => r())
  }
}

const indicatorsAnimationPlayState = computed(() =>
  (props.pauseOnHover && hovering.value) || sliding.value ? 'paused' : 'running'
)

const toIndex = (idx: number) => {
  const updateIndex = (i: number) => {
    nextTick(() => {
      emit('update:modelValue', i)
    })
  }
  if (idx < props.modelValue) {
    if (idx >= 0) {
      direction.value = 'backward'
      updateIndex(idx)
      return
    }
    if (props.infinity) {
      direction.value = 'backward'
      updateIndex(slides.value.length - 1)
    }
    return
  }
  if (idx > props.modelValue) {
    if (idx < slides.value.length) {
      direction.value = 'forward'
      updateIndex(idx)
      return
    }
    if (props.infinity) {
      direction.value = 'forward'
      updateIndex(0)
    }
  }
}
const toPrev = () => toIndex(props.modelValue - 1)
const toNext = () => toIndex(props.modelValue + 1)

const showPrev = computed(
  () => showArrow.value && (props.infinity || props.modelValue > 0)
)
const showNext = computed(
  () =>
    showArrow.value &&
    (props.infinity || props.modelValue < slides.value.length - 1)
)

provide(toNextKey, toNext)

onMounted(() => {
  resumes.forEach(r => r())
})

defineExpose({
  toIndex,
  toPrev,
  toNext,
})
</script>
<template>
  <div
    :class="['c-carousel', { 'c-carousel--vertical': vertical }]"
    :style="{
      height,
    }"
    @mouseenter="onContainerMouseEnter"
    @mouseleave="onContainerMouseLeave"
  >
    <div
      :class="[
        'c-carousel--indicators',
        'c-flex',
        `c-items-${indicatorsPositionVertical}`,
        `c-justify-${indicatorsPositionHorizontal}`,
      ]"
    >
      <div
        :class="[
          'c-carousel--indicators-container',
          'c-gutter-sm',
          'c-flex',
          `c-${indicatorsAlignDirection}`,
        ]"
      >
        <!-- 
          @slot Customize the indicators content. 
          @zh 自定义指示器内容 
        -->
        <slot name="indicators">
          <div
            v-for="(_, i) in slides"
            :key="i"
          >
            <div
              :class="[
                'c-carousel--indicator-item',
                `c-carousel--indicator-item--${theme}`,
                { 'c-carousel--indicator-item--active': i === modelValue },
              ]"
              @click="toIndex(i)"
            >
              <div class="c-carousel--indicator-item--bg" />
              <div
                class="c-carousel--indicator-item--progress-bar"
                :style="
                  i === modelValue && interval
                    ? {
                        animationPlayState: indicatorsAnimationPlayState,
                        animationName: `c-carousel-active-indicator-bar${
                          indicatorsAlignDirection.startsWith('column')
                            ? '-vertical'
                            : ''
                        }`,
                        animationDuration: `${interval}ms`,
                        animationIterationCount: 1,
                      }
                    : {}
                "
              />
            </div>
          </div>
        </slot>
      </div>
    </div>

    <Transition name="c-carousel-control">
      <div
        v-if="showPrev"
        class="c-carousel--control c-carousel--control--prev"
        @click="toPrev"
      >
        <!-- 
          @slot Customize the to previous control arrow. 
          @zh 自定义向前箭头控制器内容 
        -->
        <slot name="control-prev">
          <c-button
            icon
            flat
            :theme="theme"
          >
            <c-icon :content="outlinedNavigateBefore" />
          </c-button>
        </slot>
      </div>
    </Transition>

    <Transition name="c-carousel-control">
      <div
        v-if="showNext"
        class="c-carousel--control c-carousel--control--next"
        @click="toNext"
      >
        <!-- 
          @slot Customize the to next control arrow. 
          @zh 自定义向后箭头控制器内容 
        -->
        <slot name="control-next">
          <c-button
            icon
            flat
            :theme="theme"
          >
            <c-icon :content="outlinedNavigateNext" />
          </c-button>
        </slot>
      </div>
    </Transition>

    <div class="c-carousel--sliders">
      <!-- 
        @slot The content of carousel. It is recommended to use <code>c-carousel-slider</code>.
        @zh 轮播内容，推荐使用<code>c-carousel-slider</code>
      -->
      <slot />
    </div>
  </div>
</template>
