// packages/vue/ui/src/components/interact/CExpansion.vue
<script
  setup
  lang="ts"
>
import { ref, onMounted, computed } from 'vue'
import { CIcon } from 'casual-ui-vue'
import { matKeyboardArrowDown } from '@quasar/extras/material-icons'
import { useDefaultVModel } from '../../usable/useVModel'

interface CExpansionProps {
  /**
   * The icon string.
   * @zh 图标
   */
  icon?: string
  /**
   * The title.
   * @zh 标题
   */
  title?: string
  /**
   * The expand status. Can be used with <code>v-model</code>.
   * @zh 是否展开，用于<code>v-model</code>默认绑定
   */
  modelValue?: boolean
  /**
   * Determine whether to expand from top or not.
   * @zh 是否反向展开，如果设置为<code>true</code>则会从上方展开
   */
  reverse?: boolean
}

const props = withDefaults(defineProps<CExpansionProps>(), {
  title: '',
  modelValue: false,
  icon: '',
  reverse: false,
})

const emit = defineEmits<{
  /**
   * Emit when the expand status change.
   * @zh 展开状态变化时触发
   */
  (e: 'update:modelValue', newValue: boolean): void
}>()

const bodyDom = ref<HTMLDivElement | null>(null)
const initialBodyHeight = ref('auto')
const innerValue = ref(true)

useDefaultVModel(props, emit)

const onHeaderClick = () => {
  innerValue.value = !innerValue.value
}

onMounted(() => {
  initialBodyHeight.value = `${bodyDom.value?.clientHeight}px`
  innerValue.value = props.modelValue
})

const realtimeBodyHeigh = computed(() =>
  innerValue.value ? initialBodyHeight.value : 0
)

const setHeight = (h: number) => {
  initialBodyHeight.value = `${h}px`
}

defineExpose({
  setHeight,
})
</script>
<template>
  <div
    :class="['c-expansion', { 'c-expansion--expanded': innerValue }]"
    :style="`--casual-expansion-height:${realtimeBodyHeigh};`"
  >
    <div
      v-if="reverse"
      ref="bodyDom"
      class="c-expansion--body"
    >
      <!-- 
        @slot The expanded content. 
        @zh 默认展开内容 -->
      <slot v-bind="{ setHeight }" />
    </div>
    <div
      class="c-expansion--header"
      @click.stop="onHeaderClick"
    >
      <div
        v-if="icon || $slots.icon"
        class="c-expansion--icon"
      >
        <!-- 
          @slot Customize the icon content.
          @zh 自定义图标 -->
        <slot name="icon">
          <c-icon :content="icon" />
        </slot>
      </div>
      <div class="c-expansion--title">
        <!-- 
          @slot Customize the title content. 
          @zh 自定义标题 -->
        <slot name="title">
          {{ title }}
        </slot>
      </div>
      <div
        :class="[
          'c-expansion--arrow',
          { 'c-expansion--arrow-expanded': innerValue },
        ]"
      >
        <!-- 
          @slot Customize the arrow 
          @zh 自定义箭头 
            @binding {boolean} expand-status 当前展开状态
            @expandStatus_zh 当前展开状态
          -->
        <slot
          name="arrow"
          :expand-status="innerValue"
        >
          <c-icon
            class=""
            :content="matKeyboardArrowDown"
          />
        </slot>
      </div>
    </div>
    <div
      v-if="!reverse"
      ref="bodyDom"
      class="c-expansion--body"
    >
      <!-- 
        @slot The expanded content.
        @zh 默认展开内容 -->
      <slot v-bind="{ setHeight }" />
    </div>
  </div>
</template>

// packages/svelte/ui/src/components/CExpansion.svelte
<script>
  import clsx from 'clsx'
  import bem from '../utils/bem'
  import { createEventDispatcher, onMount, tick } from 'svelte'

  /**
   * The title of the expansion
   * @type {string}
   */
  export let title = ''

  /**
   * Determine whether the expansion is expanded or not
   * @type {boolean}
   */
  export let expanded = false

  /**
   * Determine the expand direction, `false` means down, `true` means up
   * @type {boolean}
   */
  export let reverse = false

  /**
   * The panel body dom
   */
  let bodyDom

  /**
   * The initial height of panel body
   */
  let initialBodyHeight = 'auto'

  /**
   * The real height of panel body
   */
  $: realtimeBodyHeigh = expanded ? initialBodyHeight : 0

  const dispatch = createEventDispatcher()

  function onHeaderClick() {
    expanded = !expanded
    /**
     * Emit when the expand status change
     */
    dispatch('toggle')
  }

  let initialExpaned = expanded
  if (!initialExpaned) {
    expanded = true
  }

  onMount(() => {
    initialBodyHeight = `${bodyDom.clientHeight}px`
    expanded = initialExpaned
    tick().then(() => {
      /**
       * Emit when the initial height compute is done
       */
      dispatch('ready')
    })
  })

  const setHeight = () => {}
</script>

<div
  class={bem('expansion', {
    expanded,
  })}
  style={`--casual-expansion-height:${realtimeBodyHeigh};`}
>
  {#if reverse}
    <div bind:this={bodyDom} class="c-expansion--body">
      <!-- Expansion body content -->
      <slot {setHeight} />
    </div>
  {/if}
  <!-- The header click function, emit the expand status exchange -->
  <div class="c-expansion--header" on:click|stopPropagation={onHeaderClick}>
    {#if $$slots.icon}
      <div class="c-expansion--icon">
        <!-- The content before title -->
        <slot name="icon" />
      </div>
    {/if}
    <div class="c-expansion--title">
      <!-- Customize the title content -->
      <slot name="title">
        {title}
      </slot>
    </div>
    <div
      class={clsx(
        'c-expansion--arrow',
        expanded && 'c-expansion--arrow-expanded'
      )}
    >
      <!-- Customize the arrow dom -->
      <slot name="arrow">
        <div i-ph-caret-down-light />
      </slot>
    </div>
  </div>
  {#if !reverse}
    <div bind:this={bodyDom} class="c-expansion--body">
      <!--  Expansion body content -->
      <slot {setHeight} />
    </div>
  {/if}
</div>
